// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#pragma warning(disable: 4996)

#include "simulator/corba/RDOCorba.hh"

#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>

OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
rdo::compiler::parser::RDOCorba::ParamRTP::operator>>= (cdrStream &_n) const
{
  _n.marshalString(m_name,0);
  m_type >>= _n;
  _n.marshalBoolean(m_range_int);
  m_min_int >>= _n;
  m_max_int >>= _n;
  _n.marshalBoolean(m_default_int_ch);
  m_default_int >>= _n;
  _n.marshalBoolean(m_range_double);
  m_min_double >>= _n;
  m_max_double >>= _n;
  _n.marshalBoolean(m_default_double_ch);
  m_default_double >>= _n;
  m_var_enum_count >>= _n;
  _n.marshalBoolean(m_var_enum_ch);
  (const my_enum&) m_var_enum >>= _n;
  _n.marshalBoolean(m_default_enum_ch);
  _n.marshalString(m_default_enum,0);

}

void
rdo::compiler::parser::RDOCorba::ParamRTP::operator<<= (cdrStream &_n)
{
  m_name = _n.unmarshalString(0);
  (TypeParam&)m_type <<= _n;
  m_range_int = _n.unmarshalBoolean();
  (::CORBA::Long&)m_min_int <<= _n;
  (::CORBA::Long&)m_max_int <<= _n;
  m_default_int_ch = _n.unmarshalBoolean();
  (::CORBA::Long&)m_default_int <<= _n;
  m_range_double = _n.unmarshalBoolean();
  (::CORBA::Double&)m_min_double <<= _n;
  (::CORBA::Double&)m_max_double <<= _n;
  m_default_double_ch = _n.unmarshalBoolean();
  (::CORBA::Double&)m_default_double <<= _n;
  (::CORBA::Long&)m_var_enum_count <<= _n;
  m_var_enum_ch = _n.unmarshalBoolean();
  (my_enum&)m_var_enum <<= _n;
  m_default_enum_ch = _n.unmarshalBoolean();
  m_default_enum = _n.unmarshalString(0);

}

void
rdo::compiler::parser::RDOCorba::MY_RTP::operator>>= (cdrStream &_n) const
{
  _n.marshalString(m_name,0);
  m_type >>= _n;
  m_param_count >>= _n;
  (const ParamsRTP&) m_param >>= _n;

}

void
rdo::compiler::parser::RDOCorba::MY_RTP::operator<<= (cdrStream &_n)
{
  m_name = _n.unmarshalString(0);
  (TypeRTP&)m_type <<= _n;
  (::CORBA::Long&)m_param_count <<= _n;
  (ParamsRTP&)m_param <<= _n;

}

void
rdo::compiler::parser::RDOCorba::ParamRSS::operator>>= (cdrStream &_n) const
{
  _n.marshalString(m_name,0);
  m_type >>= _n;
  m_int >>= _n;
  m_double >>= _n;
  _n.marshalString(m_enum,0);

}

void
rdo::compiler::parser::RDOCorba::ParamRSS::operator<<= (cdrStream &_n)
{
  m_name = _n.unmarshalString(0);
  (TypeParam&)m_type <<= _n;
  (::CORBA::Long&)m_int <<= _n;
  (::CORBA::Double&)m_double <<= _n;
  m_enum = _n.unmarshalString(0);

}

void
rdo::compiler::parser::RDOCorba::MY_RSS::operator>>= (cdrStream &_n) const
{
  _n.marshalString(m_name,0);
  _n.marshalString(m_type,0);
  m_param_count >>= _n;
  (const ParamsRSS&) m_param >>= _n;

}

void
rdo::compiler::parser::RDOCorba::MY_RSS::operator<<= (cdrStream &_n)
{
  m_name = _n.unmarshalString(0);
  m_type = _n.unmarshalString(0);
  (::CORBA::Long&)m_param_count <<= _n;
  (ParamsRSS&)m_param <<= _n;

}

rdo::compiler::parser::RDOCorba_ptr rdo::compiler::parser::RDOCorba_Helper::_nil() {
  return ::rdo::compiler::parser::RDOCorba::_nil();
}

::CORBA::Boolean rdo::compiler::parser::RDOCorba_Helper::is_nil(::rdo::compiler::parser::RDOCorba_ptr p) {
  return ::CORBA::is_nil(p);

}

void rdo::compiler::parser::RDOCorba_Helper::release(::rdo::compiler::parser::RDOCorba_ptr p) {
  ::CORBA::release(p);
}

void rdo::compiler::parser::RDOCorba_Helper::marshalObjRef(::rdo::compiler::parser::RDOCorba_ptr obj, cdrStream& s) {
  ::rdo::compiler::parser::RDOCorba::_marshalObjRef(obj, s);
}

rdo::compiler::parser::RDOCorba_ptr rdo::compiler::parser::RDOCorba_Helper::unmarshalObjRef(cdrStream& s) {
  return ::rdo::compiler::parser::RDOCorba::_unmarshalObjRef(s);
}

void rdo::compiler::parser::RDOCorba_Helper::duplicate(::rdo::compiler::parser::RDOCorba_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

rdo::compiler::parser::RDOCorba_ptr
rdo::compiler::parser::RDOCorba::_duplicate(::rdo::compiler::parser::RDOCorba_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

rdo::compiler::parser::RDOCorba_ptr
rdo::compiler::parser::RDOCorba::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


rdo::compiler::parser::RDOCorba_ptr
rdo::compiler::parser::RDOCorba::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

rdo::compiler::parser::RDOCorba_ptr
rdo::compiler::parser::RDOCorba::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_RDOCorba _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_RDOCorba* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_RDOCorba;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* rdo::compiler::parser::RDOCorba::_PD_repoId = "IDL:rdoParse/RDOCorba:1.0";


rdo::compiler::parser::_objref_RDOCorba::~_objref_RDOCorba() {
  
}


rdo::compiler::parser::_objref_RDOCorba::_objref_RDOCorba(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::rdo::compiler::parser::RDOCorba::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
rdo::compiler::parser::_objref_RDOCorba::_ptrToObjRef(const char* id)
{
  if( id == ::rdo::compiler::parser::RDOCorba::_PD_repoId )
    return (::rdo::compiler::parser::RDOCorba_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::rdo::compiler::parser::RDOCorba::_PD_repoId) )
    return (::rdo::compiler::parser::RDOCorba_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _crdoParse_mRDOCorba_mGetRTP_o_clong
class _0RL_cd_3765F01E8BABC70E_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_3765F01E8BABC70E_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  ::CORBA::Long arg_0;
  rdo::compiler::parser::RDOCorba::GetRTP_var result;
};

void _0RL_cd_3765F01E8BABC70E_00000000::marshalReturnedValues(cdrStream& _n)
{
  (const rdo::compiler::parser::RDOCorba::GetRTP&) result >>= _n;
  arg_0 >>= _n;

}

void _0RL_cd_3765F01E8BABC70E_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new rdo::compiler::parser::RDOCorba::GetRTP;
  (rdo::compiler::parser::RDOCorba::GetRTP&)result <<= _n;
  (::CORBA::Long&)arg_0 <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_3765F01E8BABC70E_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_3765F01E8BABC70E_00000000* tcd = (_0RL_cd_3765F01E8BABC70E_00000000*)cd;
  rdo::compiler::parser::_impl_RDOCorba* impl = (rdo::compiler::parser::_impl_RDOCorba*) svnt->_ptrToInterface(rdo::compiler::parser::RDOCorba::_PD_repoId);
  tcd->result = impl->getRDORTPlist(tcd->arg_0);


}

rdo::compiler::parser::RDOCorba::GetRTP* rdo::compiler::parser::_objref_RDOCorba::getRDORTPlist(::CORBA::Long& rtp_count)
{
  _0RL_cd_3765F01E8BABC70E_00000000 _call_desc(_0RL_lcfn_3765F01E8BABC70E_10000000, "getRDORTPlist", 14);


  _invoke(_call_desc);
  rtp_count = _call_desc.arg_0;
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _crdoParse_mRDOCorba_mGetRSS_o_clong
class _0RL_cd_3765F01E8BABC70E_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_3765F01E8BABC70E_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  ::CORBA::Long arg_0;
  rdo::compiler::parser::RDOCorba::GetRSS_var result;
};

void _0RL_cd_3765F01E8BABC70E_20000000::marshalReturnedValues(cdrStream& _n)
{
  (const rdo::compiler::parser::RDOCorba::GetRSS&) result >>= _n;
  arg_0 >>= _n;

}

void _0RL_cd_3765F01E8BABC70E_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new rdo::compiler::parser::RDOCorba::GetRSS;
  (rdo::compiler::parser::RDOCorba::GetRSS&)result <<= _n;
  (::CORBA::Long&)arg_0 <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_3765F01E8BABC70E_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_3765F01E8BABC70E_20000000* tcd = (_0RL_cd_3765F01E8BABC70E_20000000*)cd;
  rdo::compiler::parser::_impl_RDOCorba* impl = (rdo::compiler::parser::_impl_RDOCorba*) svnt->_ptrToInterface(rdo::compiler::parser::RDOCorba::_PD_repoId);
  tcd->result = impl->getRDORSSPlist(tcd->arg_0);


}

rdo::compiler::parser::RDOCorba::GetRSS* rdo::compiler::parser::_objref_RDOCorba::getRDORSSPlist(::CORBA::Long& rss_count)
{
  _0RL_cd_3765F01E8BABC70E_20000000 _call_desc(_0RL_lcfn_3765F01E8BABC70E_30000000, "getRDORSSPlist", 15);


  _invoke(_call_desc);
  rss_count = _call_desc.arg_0;
  return _call_desc.result._retn();


}
rdo::compiler::parser::_pof_RDOCorba::~_pof_RDOCorba() {}


omniObjRef*
rdo::compiler::parser::_pof_RDOCorba::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::rdo::compiler::parser::_objref_RDOCorba(ior, id);
}


::CORBA::Boolean
rdo::compiler::parser::_pof_RDOCorba::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::rdo::compiler::parser::RDOCorba::_PD_repoId) )
    return 1;
  
  return 0;
}

const rdo::compiler::parser::_pof_RDOCorba _the_pof_rdoParse_mRDOCorba;

rdo::compiler::parser::_impl_RDOCorba::~_impl_RDOCorba() {}


::CORBA::Boolean
rdo::compiler::parser::_impl_RDOCorba::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "getRDORTPlist") ) {

    _0RL_cd_3765F01E8BABC70E_00000000 _call_desc(_0RL_lcfn_3765F01E8BABC70E_10000000, "getRDORTPlist", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getRDORSSPlist") ) {

    _0RL_cd_3765F01E8BABC70E_20000000 _call_desc(_0RL_lcfn_3765F01E8BABC70E_30000000, "getRDORSSPlist", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
rdo::compiler::parser::_impl_RDOCorba::_ptrToInterface(const char* id)
{
  if( id == ::rdo::compiler::parser::RDOCorba::_PD_repoId )
    return (::rdo::compiler::parser::_impl_RDOCorba*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::rdo::compiler::parser::RDOCorba::_PD_repoId) )
    return (::rdo::compiler::parser::_impl_RDOCorba*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
rdo::compiler::parser::_impl_RDOCorba::_mostDerivedRepoId()
{
  return ::rdo::compiler::parser::RDOCorba::_PD_repoId;
}

POA_rdoParse::RDOCorba::~RDOCorba() {}

#pragma warning(default: 4996)
