// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __RDOCorba_hh__
#define __RDOCorba_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_RDOCorba
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_RDOCorba
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_RDOCorba
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE rdoParse

_CORBA_MODULE_BEG

#ifndef __rdoParse_mRDOCorba__
#define __rdoParse_mRDOCorba__

  class RDOCorba;
  class _objref_RDOCorba;
  class _impl_RDOCorba;
  
  typedef _objref_RDOCorba* RDOCorba_ptr;
  typedef RDOCorba_ptr RDOCorbaRef;

  class RDOCorba_Helper {
  public:
    typedef RDOCorba_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_RDOCorba, RDOCorba_Helper> RDOCorba_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_RDOCorba,RDOCorba_Helper > RDOCorba_out;

#endif

  // interface RDOCorba
  class RDOCorba {
  public:
    // Declarations for this interface type.
    typedef RDOCorba_ptr _ptr_type;
    typedef RDOCorba_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    enum TypeRTP { rt_permanent, rt_temporary /*, __max_TypeRTP=0xffffffff */ };
    typedef TypeRTP& TypeRTP_out;

    enum TypeParam { int_type, double_type, enum_type /*, __max_TypeParam=0xffffffff */ };
    typedef TypeParam& TypeParam_out;

    class my_enum_var;

    class my_enum : public _CORBA_Unbounded_Sequence_String {
    public:
      typedef my_enum_var _var_type;
      inline my_enum() {}
      inline my_enum(const my_enum& _s)
        : _CORBA_Unbounded_Sequence_String(_s) {}

      inline my_enum(_CORBA_ULong _max)
        : _CORBA_Unbounded_Sequence_String(_max) {}
      inline my_enum(_CORBA_ULong _max, _CORBA_ULong _len, char** _val, _CORBA_Boolean _rel=0)
        : _CORBA_Unbounded_Sequence_String(_max, _len, _val, _rel) {}

    

      inline my_enum& operator = (const my_enum& _s) {
        _CORBA_Unbounded_Sequence_String::operator=(_s);
        return *this;
      }
    };

    class my_enum_out;

    class my_enum_var {
    public:
      inline my_enum_var() : _pd_seq(0) {}
      inline my_enum_var(my_enum* _s) : _pd_seq(_s) {}
      inline my_enum_var(const my_enum_var& _s) {
        if( _s._pd_seq )  _pd_seq = new my_enum(*_s._pd_seq);
        else              _pd_seq = 0;
      }
      inline ~my_enum_var() { if( _pd_seq )  delete _pd_seq; }
        
      inline my_enum_var& operator = (my_enum* _s) {
        if( _pd_seq )  delete _pd_seq;
        _pd_seq = _s;
        return *this;
      }
      inline my_enum_var& operator = (const my_enum_var& _s) {
        if( _s._pd_seq ) {
          if( !_pd_seq )  _pd_seq = new my_enum;
          *_pd_seq = *_s._pd_seq;
        } else if( _pd_seq ) {
          delete _pd_seq;
          _pd_seq = 0;
        }
        return *this;
      }
      inline _CORBA_String_element operator [] (_CORBA_ULong _s) {
        return (*_pd_seq)[_s];
      }

    

      inline my_enum* operator -> () { return _pd_seq; }
      inline const my_enum* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
      inline operator my_enum& () const { return *_pd_seq; }
#else
      inline operator const my_enum& () const { return *_pd_seq; }
      inline operator my_enum& () { return *_pd_seq; }
#endif
        
      inline const my_enum& in() const { return *_pd_seq; }
      inline my_enum&       inout()    { return *_pd_seq; }
      inline my_enum*&      out() {
        if( _pd_seq ) { delete _pd_seq; _pd_seq = 0; }
        return _pd_seq;
      }
      inline my_enum* _retn() { my_enum* tmp = _pd_seq; _pd_seq = 0; return tmp; }
        
      friend class my_enum_out;
      
    private:
      my_enum* _pd_seq;
    };

    class my_enum_out {
    public:
      inline my_enum_out(my_enum*& _s) : _data(_s) { _data = 0; }
      inline my_enum_out(my_enum_var& _s)
        : _data(_s._pd_seq) { _s = (my_enum*) 0; }
      inline my_enum_out(const my_enum_out& _s) : _data(_s._data) {}
      inline my_enum_out& operator = (const my_enum_out& _s) {
        _data = _s._data;
        return *this;
      }
      inline my_enum_out& operator = (my_enum* _s) {
        _data = _s;
        return *this;
      }
      inline operator my_enum*&()  { return _data; }
      inline my_enum*& ptr()       { return _data; }
      inline my_enum* operator->() { return _data; }

      inline _CORBA_String_element operator [] (_CORBA_ULong _i) {
        return (*_data)[_i];
      }

    

      my_enum*& _data;

    private:
      my_enum_out();
      my_enum_out& operator=(const my_enum_var&);
    };

    struct ParamRTP {
      typedef _CORBA_ConstrType_Variable_Var<ParamRTP> _var_type;

      
      ::CORBA::String_member m_name;

      TypeParam m_type;

      ::CORBA::Boolean m_range_int;

      ::CORBA::Long m_min_int;

      ::CORBA::Long m_max_int;

      ::CORBA::Boolean m_default_int_ch;

      ::CORBA::Long m_default_int;

      ::CORBA::Boolean m_range_double;

      ::CORBA::Double m_min_double;

      ::CORBA::Double m_max_double;

      ::CORBA::Boolean m_default_double_ch;

      ::CORBA::Double m_default_double;

      ::CORBA::Long m_var_enum_count;

      ::CORBA::Boolean m_var_enum_ch;

      my_enum m_var_enum;

      ::CORBA::Boolean m_default_enum_ch;

      ::CORBA::String_member m_default_enum;

    

      void operator>>= (cdrStream &) const;
      void operator<<= (cdrStream &);
    };

    typedef ParamRTP::_var_type ParamRTP_var;

    typedef _CORBA_ConstrType_Variable_OUT_arg< ParamRTP,ParamRTP_var > ParamRTP_out;

    class ParamsRTP_var;

    class ParamsRTP : public _CORBA_Unbounded_Sequence< ParamRTP >  {
    public:
      typedef ParamsRTP_var _var_type;
      inline ParamsRTP() {}
      inline ParamsRTP(const ParamsRTP& _s)
        : _CORBA_Unbounded_Sequence< ParamRTP > (_s) {}

      inline ParamsRTP(_CORBA_ULong _max)
        : _CORBA_Unbounded_Sequence< ParamRTP > (_max) {}
      inline ParamsRTP(_CORBA_ULong _max, _CORBA_ULong _len, ParamRTP* _val, _CORBA_Boolean _rel=0)
        : _CORBA_Unbounded_Sequence< ParamRTP > (_max, _len, _val, _rel) {}

    

      inline ParamsRTP& operator = (const ParamsRTP& _s) {
        _CORBA_Unbounded_Sequence< ParamRTP > ::operator=(_s);
        return *this;
      }
    };

    class ParamsRTP_out;

    class ParamsRTP_var {
    public:
      inline ParamsRTP_var() : _pd_seq(0) {}
      inline ParamsRTP_var(ParamsRTP* _s) : _pd_seq(_s) {}
      inline ParamsRTP_var(const ParamsRTP_var& _s) {
        if( _s._pd_seq )  _pd_seq = new ParamsRTP(*_s._pd_seq);
        else              _pd_seq = 0;
      }
      inline ~ParamsRTP_var() { if( _pd_seq )  delete _pd_seq; }
        
      inline ParamsRTP_var& operator = (ParamsRTP* _s) {
        if( _pd_seq )  delete _pd_seq;
        _pd_seq = _s;
        return *this;
      }
      inline ParamsRTP_var& operator = (const ParamsRTP_var& _s) {
        if( _s._pd_seq ) {
          if( !_pd_seq )  _pd_seq = new ParamsRTP;
          *_pd_seq = *_s._pd_seq;
        } else if( _pd_seq ) {
          delete _pd_seq;
          _pd_seq = 0;
        }
        return *this;
      }
      inline ParamRTP& operator [] (_CORBA_ULong _s) {
        return (*_pd_seq)[_s];
      }

    

      inline ParamsRTP* operator -> () { return _pd_seq; }
      inline const ParamsRTP* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
      inline operator ParamsRTP& () const { return *_pd_seq; }
#else
      inline operator const ParamsRTP& () const { return *_pd_seq; }
      inline operator ParamsRTP& () { return *_pd_seq; }
#endif
        
      inline const ParamsRTP& in() const { return *_pd_seq; }
      inline ParamsRTP&       inout()    { return *_pd_seq; }
      inline ParamsRTP*&      out() {
        if( _pd_seq ) { delete _pd_seq; _pd_seq = 0; }
        return _pd_seq;
      }
      inline ParamsRTP* _retn() { ParamsRTP* tmp = _pd_seq; _pd_seq = 0; return tmp; }
        
      friend class ParamsRTP_out;
      
    private:
      ParamsRTP* _pd_seq;
    };

    class ParamsRTP_out {
    public:
      inline ParamsRTP_out(ParamsRTP*& _s) : _data(_s) { _data = 0; }
      inline ParamsRTP_out(ParamsRTP_var& _s)
        : _data(_s._pd_seq) { _s = (ParamsRTP*) 0; }
      inline ParamsRTP_out(const ParamsRTP_out& _s) : _data(_s._data) {}
      inline ParamsRTP_out& operator = (const ParamsRTP_out& _s) {
        _data = _s._data;
        return *this;
      }
      inline ParamsRTP_out& operator = (ParamsRTP* _s) {
        _data = _s;
        return *this;
      }
      inline operator ParamsRTP*&()  { return _data; }
      inline ParamsRTP*& ptr()       { return _data; }
      inline ParamsRTP* operator->() { return _data; }

      inline ParamRTP& operator [] (_CORBA_ULong _i) {
        return (*_data)[_i];
      }

    

      ParamsRTP*& _data;

    private:
      ParamsRTP_out();
      ParamsRTP_out& operator=(const ParamsRTP_var&);
    };

    struct MY_RTP {
      typedef _CORBA_ConstrType_Variable_Var<MY_RTP> _var_type;

      
      ::CORBA::String_member m_name;

      TypeRTP m_type;

      ::CORBA::Long m_param_count;

      ParamsRTP m_param;

    

      void operator>>= (cdrStream &) const;
      void operator<<= (cdrStream &);
    };

    typedef MY_RTP::_var_type MY_RTP_var;

    typedef _CORBA_ConstrType_Variable_OUT_arg< MY_RTP,MY_RTP_var > MY_RTP_out;

    class GetRTP_var;

    class GetRTP : public _CORBA_Unbounded_Sequence< MY_RTP >  {
    public:
      typedef GetRTP_var _var_type;
      inline GetRTP() {}
      inline GetRTP(const GetRTP& _s)
        : _CORBA_Unbounded_Sequence< MY_RTP > (_s) {}

      inline GetRTP(_CORBA_ULong _max)
        : _CORBA_Unbounded_Sequence< MY_RTP > (_max) {}
      inline GetRTP(_CORBA_ULong _max, _CORBA_ULong _len, MY_RTP* _val, _CORBA_Boolean _rel=0)
        : _CORBA_Unbounded_Sequence< MY_RTP > (_max, _len, _val, _rel) {}

    

      inline GetRTP& operator = (const GetRTP& _s) {
        _CORBA_Unbounded_Sequence< MY_RTP > ::operator=(_s);
        return *this;
      }
    };

    class GetRTP_out;

    class GetRTP_var {
    public:
      inline GetRTP_var() : _pd_seq(0) {}
      inline GetRTP_var(GetRTP* _s) : _pd_seq(_s) {}
      inline GetRTP_var(const GetRTP_var& _s) {
        if( _s._pd_seq )  _pd_seq = new GetRTP(*_s._pd_seq);
        else              _pd_seq = 0;
      }
      inline ~GetRTP_var() { if( _pd_seq )  delete _pd_seq; }
        
      inline GetRTP_var& operator = (GetRTP* _s) {
        if( _pd_seq )  delete _pd_seq;
        _pd_seq = _s;
        return *this;
      }
      inline GetRTP_var& operator = (const GetRTP_var& _s) {
        if( _s._pd_seq ) {
          if( !_pd_seq )  _pd_seq = new GetRTP;
          *_pd_seq = *_s._pd_seq;
        } else if( _pd_seq ) {
          delete _pd_seq;
          _pd_seq = 0;
        }
        return *this;
      }
      inline MY_RTP& operator [] (_CORBA_ULong _s) {
        return (*_pd_seq)[_s];
      }

    

      inline GetRTP* operator -> () { return _pd_seq; }
      inline const GetRTP* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
      inline operator GetRTP& () const { return *_pd_seq; }
#else
      inline operator const GetRTP& () const { return *_pd_seq; }
      inline operator GetRTP& () { return *_pd_seq; }
#endif
        
      inline const GetRTP& in() const { return *_pd_seq; }
      inline GetRTP&       inout()    { return *_pd_seq; }
      inline GetRTP*&      out() {
        if( _pd_seq ) { delete _pd_seq; _pd_seq = 0; }
        return _pd_seq;
      }
      inline GetRTP* _retn() { GetRTP* tmp = _pd_seq; _pd_seq = 0; return tmp; }
        
      friend class GetRTP_out;
      
    private:
      GetRTP* _pd_seq;
    };

    class GetRTP_out {
    public:
      inline GetRTP_out(GetRTP*& _s) : _data(_s) { _data = 0; }
      inline GetRTP_out(GetRTP_var& _s)
        : _data(_s._pd_seq) { _s = (GetRTP*) 0; }
      inline GetRTP_out(const GetRTP_out& _s) : _data(_s._data) {}
      inline GetRTP_out& operator = (const GetRTP_out& _s) {
        _data = _s._data;
        return *this;
      }
      inline GetRTP_out& operator = (GetRTP* _s) {
        _data = _s;
        return *this;
      }
      inline operator GetRTP*&()  { return _data; }
      inline GetRTP*& ptr()       { return _data; }
      inline GetRTP* operator->() { return _data; }

      inline MY_RTP& operator [] (_CORBA_ULong _i) {
        return (*_data)[_i];
      }

    

      GetRTP*& _data;

    private:
      GetRTP_out();
      GetRTP_out& operator=(const GetRTP_var&);
    };

    struct ParamRSS {
      typedef _CORBA_ConstrType_Variable_Var<ParamRSS> _var_type;

      
      ::CORBA::String_member m_name;

      TypeParam m_type;

      ::CORBA::Long m_int;

      ::CORBA::Double m_double;

      ::CORBA::String_member m_enum;

    

      void operator>>= (cdrStream &) const;
      void operator<<= (cdrStream &);
    };

    typedef ParamRSS::_var_type ParamRSS_var;

    typedef _CORBA_ConstrType_Variable_OUT_arg< ParamRSS,ParamRSS_var > ParamRSS_out;

    class ParamsRSS_var;

    class ParamsRSS : public _CORBA_Unbounded_Sequence< ParamRSS >  {
    public:
      typedef ParamsRSS_var _var_type;
      inline ParamsRSS() {}
      inline ParamsRSS(const ParamsRSS& _s)
        : _CORBA_Unbounded_Sequence< ParamRSS > (_s) {}

      inline ParamsRSS(_CORBA_ULong _max)
        : _CORBA_Unbounded_Sequence< ParamRSS > (_max) {}
      inline ParamsRSS(_CORBA_ULong _max, _CORBA_ULong _len, ParamRSS* _val, _CORBA_Boolean _rel=0)
        : _CORBA_Unbounded_Sequence< ParamRSS > (_max, _len, _val, _rel) {}

    

      inline ParamsRSS& operator = (const ParamsRSS& _s) {
        _CORBA_Unbounded_Sequence< ParamRSS > ::operator=(_s);
        return *this;
      }
    };

    class ParamsRSS_out;

    class ParamsRSS_var {
    public:
      inline ParamsRSS_var() : _pd_seq(0) {}
      inline ParamsRSS_var(ParamsRSS* _s) : _pd_seq(_s) {}
      inline ParamsRSS_var(const ParamsRSS_var& _s) {
        if( _s._pd_seq )  _pd_seq = new ParamsRSS(*_s._pd_seq);
        else              _pd_seq = 0;
      }
      inline ~ParamsRSS_var() { if( _pd_seq )  delete _pd_seq; }
        
      inline ParamsRSS_var& operator = (ParamsRSS* _s) {
        if( _pd_seq )  delete _pd_seq;
        _pd_seq = _s;
        return *this;
      }
      inline ParamsRSS_var& operator = (const ParamsRSS_var& _s) {
        if( _s._pd_seq ) {
          if( !_pd_seq )  _pd_seq = new ParamsRSS;
          *_pd_seq = *_s._pd_seq;
        } else if( _pd_seq ) {
          delete _pd_seq;
          _pd_seq = 0;
        }
        return *this;
      }
      inline ParamRSS& operator [] (_CORBA_ULong _s) {
        return (*_pd_seq)[_s];
      }

    

      inline ParamsRSS* operator -> () { return _pd_seq; }
      inline const ParamsRSS* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
      inline operator ParamsRSS& () const { return *_pd_seq; }
#else
      inline operator const ParamsRSS& () const { return *_pd_seq; }
      inline operator ParamsRSS& () { return *_pd_seq; }
#endif
        
      inline const ParamsRSS& in() const { return *_pd_seq; }
      inline ParamsRSS&       inout()    { return *_pd_seq; }
      inline ParamsRSS*&      out() {
        if( _pd_seq ) { delete _pd_seq; _pd_seq = 0; }
        return _pd_seq;
      }
      inline ParamsRSS* _retn() { ParamsRSS* tmp = _pd_seq; _pd_seq = 0; return tmp; }
        
      friend class ParamsRSS_out;
      
    private:
      ParamsRSS* _pd_seq;
    };

    class ParamsRSS_out {
    public:
      inline ParamsRSS_out(ParamsRSS*& _s) : _data(_s) { _data = 0; }
      inline ParamsRSS_out(ParamsRSS_var& _s)
        : _data(_s._pd_seq) { _s = (ParamsRSS*) 0; }
      inline ParamsRSS_out(const ParamsRSS_out& _s) : _data(_s._data) {}
      inline ParamsRSS_out& operator = (const ParamsRSS_out& _s) {
        _data = _s._data;
        return *this;
      }
      inline ParamsRSS_out& operator = (ParamsRSS* _s) {
        _data = _s;
        return *this;
      }
      inline operator ParamsRSS*&()  { return _data; }
      inline ParamsRSS*& ptr()       { return _data; }
      inline ParamsRSS* operator->() { return _data; }

      inline ParamRSS& operator [] (_CORBA_ULong _i) {
        return (*_data)[_i];
      }

    

      ParamsRSS*& _data;

    private:
      ParamsRSS_out();
      ParamsRSS_out& operator=(const ParamsRSS_var&);
    };

    struct MY_RSS {
      typedef _CORBA_ConstrType_Variable_Var<MY_RSS> _var_type;

      
      ::CORBA::String_member m_name;

      ::CORBA::String_member m_type;

      ::CORBA::Long m_param_count;

      ParamsRSS m_param;

    

      void operator>>= (cdrStream &) const;
      void operator<<= (cdrStream &);
    };

    typedef MY_RSS::_var_type MY_RSS_var;

    typedef _CORBA_ConstrType_Variable_OUT_arg< MY_RSS,MY_RSS_var > MY_RSS_out;

    class GetRSS_var;

    class GetRSS : public _CORBA_Unbounded_Sequence< MY_RSS >  {
    public:
      typedef GetRSS_var _var_type;
      inline GetRSS() {}
      inline GetRSS(const GetRSS& _s)
        : _CORBA_Unbounded_Sequence< MY_RSS > (_s) {}

      inline GetRSS(_CORBA_ULong _max)
        : _CORBA_Unbounded_Sequence< MY_RSS > (_max) {}
      inline GetRSS(_CORBA_ULong _max, _CORBA_ULong _len, MY_RSS* _val, _CORBA_Boolean _rel=0)
        : _CORBA_Unbounded_Sequence< MY_RSS > (_max, _len, _val, _rel) {}

    

      inline GetRSS& operator = (const GetRSS& _s) {
        _CORBA_Unbounded_Sequence< MY_RSS > ::operator=(_s);
        return *this;
      }
    };

    class GetRSS_out;

    class GetRSS_var {
    public:
      inline GetRSS_var() : _pd_seq(0) {}
      inline GetRSS_var(GetRSS* _s) : _pd_seq(_s) {}
      inline GetRSS_var(const GetRSS_var& _s) {
        if( _s._pd_seq )  _pd_seq = new GetRSS(*_s._pd_seq);
        else              _pd_seq = 0;
      }
      inline ~GetRSS_var() { if( _pd_seq )  delete _pd_seq; }
        
      inline GetRSS_var& operator = (GetRSS* _s) {
        if( _pd_seq )  delete _pd_seq;
        _pd_seq = _s;
        return *this;
      }
      inline GetRSS_var& operator = (const GetRSS_var& _s) {
        if( _s._pd_seq ) {
          if( !_pd_seq )  _pd_seq = new GetRSS;
          *_pd_seq = *_s._pd_seq;
        } else if( _pd_seq ) {
          delete _pd_seq;
          _pd_seq = 0;
        }
        return *this;
      }
      inline MY_RSS& operator [] (_CORBA_ULong _s) {
        return (*_pd_seq)[_s];
      }

    

      inline GetRSS* operator -> () { return _pd_seq; }
      inline const GetRSS* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
      inline operator GetRSS& () const { return *_pd_seq; }
#else
      inline operator const GetRSS& () const { return *_pd_seq; }
      inline operator GetRSS& () { return *_pd_seq; }
#endif
        
      inline const GetRSS& in() const { return *_pd_seq; }
      inline GetRSS&       inout()    { return *_pd_seq; }
      inline GetRSS*&      out() {
        if( _pd_seq ) { delete _pd_seq; _pd_seq = 0; }
        return _pd_seq;
      }
      inline GetRSS* _retn() { GetRSS* tmp = _pd_seq; _pd_seq = 0; return tmp; }
        
      friend class GetRSS_out;
      
    private:
      GetRSS* _pd_seq;
    };

    class GetRSS_out {
    public:
      inline GetRSS_out(GetRSS*& _s) : _data(_s) { _data = 0; }
      inline GetRSS_out(GetRSS_var& _s)
        : _data(_s._pd_seq) { _s = (GetRSS*) 0; }
      inline GetRSS_out(const GetRSS_out& _s) : _data(_s._data) {}
      inline GetRSS_out& operator = (const GetRSS_out& _s) {
        _data = _s._data;
        return *this;
      }
      inline GetRSS_out& operator = (GetRSS* _s) {
        _data = _s;
        return *this;
      }
      inline operator GetRSS*&()  { return _data; }
      inline GetRSS*& ptr()       { return _data; }
      inline GetRSS* operator->() { return _data; }

      inline MY_RSS& operator [] (_CORBA_ULong _i) {
        return (*_data)[_i];
      }

    

      GetRSS*& _data;

    private:
      GetRSS_out();
      GetRSS_out& operator=(const GetRSS_var&);
    };

  
  };

  class _objref_RDOCorba :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    RDOCorba::GetRTP* getRDORTPlist(::CORBA::Long& rtp_count);
    RDOCorba::GetRSS* getRDORSSPlist(::CORBA::Long& rss_count);

    inline _objref_RDOCorba()  { _PR_setobj(0); }  // nil
    _objref_RDOCorba(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_RDOCorba();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_RDOCorba(const _objref_RDOCorba&);
    _objref_RDOCorba& operator = (const _objref_RDOCorba&);
    // not implemented

    friend class RDOCorba;
  };

  class _pof_RDOCorba : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_RDOCorba() : _OMNI_NS(proxyObjectFactory)(RDOCorba::_PD_repoId) {}
    virtual ~_pof_RDOCorba();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_RDOCorba :
    public virtual omniServant
  {
  public:
    virtual ~_impl_RDOCorba();

    virtual RDOCorba::GetRTP* getRDORTPlist(::CORBA::Long& rtp_count) = 0;
    virtual RDOCorba::GetRSS* getRDORSSPlist(::CORBA::Long& rss_count) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_rdoParse
_CORBA_MODULE_BEG

  class RDOCorba :
    public virtual rdoParser::_impl_RDOCorba,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~RDOCorba();

    inline ::rdoParser::RDOCorba_ptr _this() {
      return (::rdoParser::RDOCorba_ptr) _do_this(::rdoParser::RDOCorba::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_rdoParse
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

inline void operator >>=(rdoParser::RDOCorba::TypeRTP _e, cdrStream& s) {
  ::operator>>=((::CORBA::ULong)_e, s);
}

inline void operator <<= (rdoParser::RDOCorba::TypeRTP& _e, cdrStream& s) {
  ::CORBA::ULong _0RL_e;
  ::operator<<=(_0RL_e,s);
  if (_0RL_e <= rdoParser::RDOCorba::rt_temporary) {
    _e = (rdoParser::RDOCorba::TypeRTP) _0RL_e;
  }
  else {
    OMNIORB_THROW(MARSHAL,_OMNI_NS(MARSHAL_InvalidEnumValue),
                  (::CORBA::CompletionStatus)s.completion());
  }
}

inline void operator >>=(rdoParser::RDOCorba::TypeParam _e, cdrStream& s) {
  ::operator>>=((::CORBA::ULong)_e, s);
}

inline void operator <<= (rdoParser::RDOCorba::TypeParam& _e, cdrStream& s) {
  ::CORBA::ULong _0RL_e;
  ::operator<<=(_0RL_e,s);
  if (_0RL_e <= rdoParser::RDOCorba::enum_type) {
    _e = (rdoParser::RDOCorba::TypeParam) _0RL_e;
  }
  else {
    OMNIORB_THROW(MARSHAL,_OMNI_NS(MARSHAL_InvalidEnumValue),
                  (::CORBA::CompletionStatus)s.completion());
  }
}



inline void
rdoParser::RDOCorba::_marshalObjRef(::rdoParser::RDOCorba_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_RDOCorba
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_RDOCorba
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_RDOCorba
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_RDOCorba
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_RDOCorba
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_RDOCorba
#endif

#endif  // __RDOCorba_hh__

