//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Telacon32.rc
//
#define IDS_PROGRAM_ROOT                489
#define IDS_KEY_PLACEMENT_FLAGS         490
#define IDS_KEY_PLACEMENT_SHOWCMD       491
#define IDS_KEY_PLACEMENT_MINPOSITION_X 492
#define IDS_KEY_PLACEMENT_MINPOSITION_Y 493
#define IDS_KEY_PLACEMENT_MAXPOSITION_X 494
#define IDS_KEY_PLACEMENT_MAXPOSITION_Y 495
#define IDS_KEY_PLACEMENT_NORMAL_LEFT   496
#define IDS_KEY_PLACEMENT_NORMAL_RIGHT  497
#define IDS_KEY_PLACEMENT_NORMAL_TOP    498
#define IDS_KEY_PLACEMENT_NORMAL_BOTTOM 499
