//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by chat.rc
//
#define IDR_MAINFRAME                   128
#define IDB_STATUSMODE                  131
#define IDD_OPTIONS_GENERAL_DIALOG      136
#define IDR_INCOMINGMESSAGE_WAVE        142
#define IDR_CHATRET_WAVE                147
#define IDR_CHATTYPE_WAVE               148
#define IDR_CHATBACK_WAVE               149
#define IDR_CONNECT_WAVE                151
#define IDR_DISCONNECT_WAVE             152
#define IDR_CHANGESTATUSMODE_WAVE       153
#define IDI_TRAY_APP                    156
#define IDI_TRAY_MESSAGE                157
#define IDR_TRAY_MENU                   159
#define IDD_OPTIONS_SOUND_DIALOG        163
#define IDB_SOUND                       164
#define IDD_POPUP_DIALOG                168
#define IDD_OPTIONS_STATUSMODE_DIALOG   170
#define IDD_STATUSMODEINFO_DIALOG       171
#define IDD_MESSAGE_DIALOG              173
#define IDB_NET                         180
#define IDR_NETWORK_MENU                181
#define IDR_STATUSMODE_TOOLBAR          189
#define IDR_MAIN_TOOLBAR                191
#define IDB_STATISMODE_TOOLBAR_D        193
#define IDR_PRIVATEMSG_WAVE             195
#define IDR_USER_MENU                   196
#define IDB_MAIN_TOOLBAR_D              197
#define IDR_SMILE_SMILE                 214
#define IDR_SMILE_FROWN                 215
#define IDR_SMILE_TOMATO                216
#define IDR_SMILE_WINK                  217
#define IDR_SMILE_SMIRK                 218
#define IDR_SMILE_TONGUE                219
#define IDR_SMILE_BIGGRIN               220
#define IDR_SMILE_GIGI                  221
#define IDR_SMILE_EYES                  222
#define IDR_SMILE_BEER                  223
#define IDR_SMILE_FRIDAY                224
#define IDR_SMILE_LAMER                 225
#define IDR_SMILE_LAUGH                 226
#define IDR_SMILE_LOL                   227
#define IDR_SMILE_COOL                  228
#define IDR_SMILE_CONFUSED              229
#define IDR_SMILE_EEK                   230
#define IDR_SMILE_ROLLEYES              231
#define IDR_SMILE_INSANE                232
#define IDR_SMILE_REDFACE               233
#define IDR_SMILE_MAD                   234
#define IDR_SMILE_WEEP                  235
#define IDR_SMILE_UP                    236
#define IDR_SMILE_DOWN                  237
#define IDR_SMILE_ROTATE                238
#define IDR_SMILE_SUPER                 239
#define IDR_SMILE_UPSET                 240
#define IDR_SMILE_AMAZED                241
#define IDR_SMILE_SHUFFLE               242
#define IDR_SMILE_SPY                   243
#define IDR_SMILE_IDEA                  244
#define IDR_SMILE_PUKE                  245
#define IDR_SMILE_WINK2                 246
#define IDR_SMILE_SMIRK2                247
#define IDR_SMILE_THINK                 248
#define IDR_SMILE_FEAR                  249
#define IDR_SMILE_YES                   250
#define IDR_SMILE_NO                    251
#define IDR_SMILE_CRAZY                 252
#define IDR_SMILE_JOKE                  253
#define IDR_SMILE_HAH                   254
#define IDR_SMILE_BALLET                255
#define IDR_SMILE_DRINK                 256
#define IDR_SMILE_FART                  257
#define IDR_SMILE_BOX                   258
#define IDR_SMILE_INVALID               259
#define IDR_SMILE_DUEL                  261
#define IDR_SMILE_KOS                   262
#define IDR_SMILE_GOSSIP                263
#define IDR_SMILE_BIS                   264
#define IDR_SMILE_HIT                   265
#define IDR_SMILE_IVAN                  266
#define IDR_SMILE_VENERA                267
#define IDR_SMILE_MOBILE                268
#define IDR_SMILE_KULT                  269
#define IDR_SMILE_FIGA                  270
#define IDD_ABOUT                       271
#define IDR_EDIT_TOOLBAR                278
#define IDB_EDIT_TOOLBAR_D              280
#define IDB_DOCK                        281
#define IDD_INIT                        282
#define IDC_USERNAME_EDIT               1000
#define IDC_USERNAME_STATIC             1001
#define IDC_USER_GROUPBOX               1003
#define IDC_CLOSEBUTTON_GROUPBOX        1004
#define IDC_CLOSEBUTTON_CLOSE_RADIO     1005
#define IDC_CLOSEBUTTON_MINIMIZE_RADIO  1006
#define IDC_CLOSEBUTTON_TRAY_RADIO      1007
#define IDC_MINIMIZEBUTTON_MINIMIZE_RADIO 1008
#define IDC_MINIMIZEBUTTON_TRAY_RADIO   1009
#define IDC_MINIMIZEBUTTON_GROUPBOX     1010
#define IDC_TRAYUSE_CHECK               1011
#define IDC_TRAYNOTIFY_CHECK            1012
#define IDC_TRAY_GROUPBOX               1013
#define IDC_SOUNDUSE_CHECK              1014
#define IDC_SOUND_LIST                  1015
#define IDC_SOUNDDEFAULT_RADIO          1016
#define IDC_SOUNDEXTERNAL_RADIO         1017
#define IDC_SOUNDNONE_RADIO             1018
#define IDC_SOUNDEXTERNAL_EDIT          1019
#define IDC_SOUNDEXTERMAL_BUTTON        1020
#define IDC_POPUPUSE_CHECK              1021
#define IDC_POPUPPOSITION_COMBO         1022
#define IDC_POPUPDELAY_SPIN             1023
#define IDC_POPUPDELAY_EDIT             1024
#define IDC_POPUPTEXTCOLOR_COMBO        1026
#define IDC_POPUPBACKGROUNDCOLOR_COMBO  1027
#define IDC_POPUP_GROUPBOX              1028
#define IDC_POPUPPOSITION_STATIC        1029
#define IDC_POPUPDELAY_STATIC           1030
#define IDC_POPUPTEXTCOLOR_STATIC       1031
#define IDC_POPUPTEXTCOLOR_BUTTON       1032
#define IDC_POPUPBACKGROUNDCOLOR_BUTTON 1033
#define IDC_POPUPBACKGROUNDCOLOR_STATIC 1034
#define IDC_STATUSMODE_LIST             1035
#define IDC_STATUSMODENAME_EDIT         1036
#define IDC_STATUSMODEINFO_EDIT         1037
#define IDC_STATUSMODENAME_STATIC       1038
#define IDC_STATUSMODEINFO_STATIC       1039
#define IDC_INFO_EDIT                   1040
#define IDC_INFO_STATIC                 1041
#define IDC_INFO_CHECK                  1042
#define IDC_AUTOMATICALLYSTATUSMODE_STATIC 1046
#define IDC_AUTOMATICALLYSTATUSMODE_AWAY_CHECK 1047
#define IDC_AUTOMATICALLYSTATUSMODE_AWAY_EDIT 1048
#define IDC_AUTOMATICALLYSTATUSMODE_AWAY_SPIN 1049
#define IDC_AUTOMATICALLYSTATUSMODE_AWAY_STATIC 1050
#define IDC_AUTOMATICALLYSTATUSMODE_NOTAVAILIBLE_CHECK 1051
#define IDC_AUTOMATICALLYSTATUSMODE_NOTAVAILIBLE_EDIT 1052
#define IDC_MESSAGE_EDIT                1052
#define IDC_AUTOMATICALLYSTATUSMODE_NOTAVAILIBLE_SPIN 1053
#define IDC_BUILD_STATIC                1053
#define IDC_AUTOMATICALLYSTATUSMODE_NOTAVAILIBLE_STATIC 1054
#define IDC_AUTHOR_STATIC               1054
#define IDC_EMAIL_STATIC                1055
#define IDC_IMAGE_STATIC                1056
#define ID_STATUSMODE_ONLINE            32773
#define ID_STATUSMODE_AWAY              32776
#define ID_STATUSMODE_NOTAVAILIBLE      32778
#define ID_TRAYMENU_OPEN                32782
#define ID_TRAYMENU_EXIT                32783
#define ID_CHAT_TOCRYOUT                32793
#define ID_FILE_REFRESHUSERLIST         32794
#define ID_STATUSMODE_ONLINE_INFO       32795
#define ID_STATUSMODE_AWAY_INFO         32796
#define ID_STATUSMODE_NOTAVAILIBLE_INFO 32797
#define ID_CHAT_OPTIONS                 32798
#define ID_FILE_REFRESHNETWORK          32801
#define ID_NETWORK_OPEN                 32803
#define ID_NETWORK_INFO                 32804
#define ID_VIEW_DOCKWINDOW              32805
#define ID_VIEW_STATUSMODE_TOOLBAR      32814
#define ID_VIEW_MAINTOOLBAR             32815
#define ID_SOUND                        32823
#define ID_USER_SENDMESSAGE             32827
#define ID_USER_INGNORE                 32828
#define ID_HELP_ABOUT                   32841
#define ID_HELP_CONTENTS                32842
#define ID_VIEW_EDITTOOLBAR             32850
#define ID_VIEW_STATUSBAR               32851
#define ID_SHOW_USERLIST                32852
#define ID_SHOW_NETWORK                 32853
#define ID_SHOW_SMILES                  32854
#define ID_SHOW_EDIT                    32855
#define IDS_INFOSTATUSBAR               59394
#define IDS_STATUSMODE_TOOLBAR          61204
#define IDS_OPTIONS                     61205
#define IDS_CONNECT_WAVE                61206
#define IDS_DISCONNECT_WAVE             61207
#define IDS_CHANGESTATUSMODE_WAVE       61208
#define IDS_INCOMINGMESSAGE_WAVE        61209
#define IDS_CHATTYPE_WAVE               61210
#define IDS_CHATBACK_WAVE               61211
#define IDS_CHATRET_WAVE                61212
#define IDS_STATUSMODE_ONLINE           61213
#define IDS_STATUSMODE_AWAY             61214
#define IDS_STATUSMODE_NOTAVAILIBLE     61215
#define IDS_STATUSMODE_VIEWERLOG        61216
#define IDS_STATUSMODEWITHINFO_VIEWERLOG 61217
#define IDS_CONNECT_VIEWERLOG           61218
#define IDS_DISCONNECT_VIEWERLOG        61219
#define IDS_STATUSMODE_CHANGEAUTOMATICALLY 61220
#define IDS_DOCKWINDOW                  61221
#define IDS_HOSTNAME_VALUE              61222
#define IDS_IP_VALUE                    61223
#define IDS_USERS                       61224
#define IDS_NETWORK                     61225
#define IDS_MAIN_TOOLBAR                61226
#define IDS_TOCRYOUT_DIALOG             61227
#define IDS_SENDMESSAGE_DIALOG          61228
#define IDS_POPUPMESSAGE_WAVE           61229
#define IDS_PRIVATEMESSAGE_WAVE         61229
#define IDS_NO_HELP_FILE                61230
#define IDS_EDIT_TOOLBAR                61231
#define IDS_SMILES                      61232
#define IDS_IP_UNKNOW                   61233
#define IDS_STATUSINFO_VALUE            61234
#define IDS_CHANGENAME_VIEWERLOG        61235
#define IDS_SPLASH_INITINFO             61236
#define IDS_SPLASH_INITINFO_FONT        61237
#define IDS_SPLASH_INITINFO_SOCKET      61238
#define IDS_SPLASH_INITINFO_SMILES      61239
#define IDS_SPLASH_RUNNING              61240
#define IDS_SMILE_SMILE                 61241
#define IDS_SMILE_FROWN                 61242
#define IDS_SMILE_WINK                  61243
#define IDS_SMILE_SMIRK                 61244
#define IDS_SMILE_TONGUE                61245
#define IDS_SMILE_BIGGRIN               61246
#define IDS_SMILE_GIGI                  61247
#define IDS_SMILE_LAUGH                 61248
#define IDS_SMILE_LOL                   61249
#define IDS_SMILE_COOL                  61250
#define IDS_SMILE_CONFUSED              61251
#define IDS_SMILE_EEK                   61252
#define IDS_SMILE_ROLLEYES              61253
#define IDS_SMILE_INSANE                61254
#define IDS_SMILE_REDFACE               61255
#define IDS_SMILE_MAD                   61256
#define IDS_SMILE_WEEP                  61257
#define IDS_SMILE_UP                    61258
#define IDS_SMILE_DOWN                  61259
#define IDS_SMILE_ROTATE                61260
#define IDS_SMILE_SUPER                 61261
#define IDS_SMILE_UPSET                 61262
#define IDS_SMILE_BEER                  61263
#define IDS_SMILE_AMAZED                61264
#define IDS_SMILE_SHUFFLE               61265
#define IDS_SMILE_LAMER                 61266
#define IDS_SMILE_SPY                   61267
#define IDS_SMILE_IDEA                  61268
#define IDS_SMILE_PUKE                  61269
#define IDS_SMILE_WINK2                 61270
#define IDS_SMILE_SMIRK2                61271
#define IDS_SMILE_THINK                 61272
#define IDS_SMILE_FEAR                  61273
#define IDS_SMILE_YES                   61274
#define IDS_SMILE_NO                    61275
#define IDS_SMILE_CRAZY                 61276
#define IDS_SMILE_JOKE                  61277
#define IDS_SMILE_HAH                   61278
#define IDS_SMILE_BALLET                61279
#define IDS_SMILE_FRIDAY                61280
#define IDS_SMILE_DRINK                 61281
#define IDS_SMILE_FART                  61282
#define IDS_SMILE_BOX                   61283
#define IDS_SMILE_INVALID               61284
#define IDS_SMILE_DUEL                  61285
#define IDS_SMILE_KOS                   61286
#define IDS_SMILE_GOSSIP                61287
#define IDS_SMILE_BIS                   61288
#define IDS_SMILE_HIT                   61289
#define IDS_SMILE_IVAN                  61290
#define IDS_SMILE_VENERA                61291
#define IDS_SMILE_MOBILE                61292
#define IDS_SMILE_KULT                  61293
#define IDS_SMILE_FIGA                  61294
#define IDS_SMILE_EYES                  61295
#define IDS_SMILE_TOMATO                61296
#define IDS_SOCKET_ERROR_INIT           61297
#define IDS_SOCKET_ERROR_CRETAE         61298
#define IDS_SOCKET_ERROR_SETBROADCAST   61299
#define IDS_SOCKET_ERROR_GETBROADCAST   61300

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        283
#define _APS_NEXT_COMMAND_VALUE         32856
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
