//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by rdo_tracer.rc
//
#define IDS_CAPTION                     1
#define ID_MODEL_START                  2
#define ID_RESOURCE_TYPES               3
#define ID_RESULTS                      4
#define ID_MODEL                        5
#define IDS_OPTIONS                     31
#define IDS_LOG_SAMPLE                  32
#define IDS_TRACE_TOOLBAR               33
#define IDS_LOG_TOOLBAR                 34
#define ID_MSG_CANTFIND                 35
#define ID_PATTERNS                     36
#define ID_RAO_CLIPBRD                  37
#define ID_COORD_STATUSBAR              38
#define ID_MODIFY_STATUSBAR             39
#define IDS_CHART_TITLE                 41
#define IDS_CHART_OPTIONS_APPLY         42
#define IDS_CHART_OPTIONS               43
#define IDS_TRACE_FILTER                44
#define IDS_ZOOM_TOOLBAR                45
#define IDS_COLORSTYLE_ALLWINDOW        46
#define IDR_MAINFRAME                   128
#define ID_MSG_NO_HELP_FILE             129
#define IDB_TREECTRL                    130
#define ID_STATUSBAR_READONLY           130
#define IDR_TRACE_TOOLBAR               134
#define IDB_TRACE_TOOLBAR_D             136
#define IDR_LOG_TOOLBAR                 137
#define IDB_LOG_TOOLBAR_D               139
#define IDD_CHART_OPTIONS_CHART         140
#define IDD_CHART_OPTIONS_SERIES        141
#define IDR_ZOOM_TOOLBAR                145
#define IDB_ZOOM_TOOLBAR_D              147
#define IDD_OPTIONS_STYLESANDCOLORS     153
#define IDC_STYLEITEM_TREE              1002
#define IDC_THEME_STATIC                1007
#define IDC_PREVIEWAS_STATIC            1009
#define IDC_THEME_COMBO                 1012
#define IDC_PREVIEWAS_COMBO             1013
#define IDC_CHART_TITLE_STATIC          1021
#define IDC_CHART_TITLE_EDIT            1022
#define IDC_VAL_COUNT_Y_STATIC          1023
#define IDC_IDC_VAL_COUNT_Y_EDIT        1024
#define IDC_FONTNAME_COMBO              1024
#define IDC_VAL_COUNT_X_STATIC          1025
#define IDC_FONTSIZE_COMBO              1025
#define IDC_IDC_VAL_COUNT_X_EDIT        1026
#define IDC_FONTBOLD_CHECK              1026
#define IDC_AXIS_VAL_STATIC             1027
#define IDC_FONTITALIC_CHECK            1027
#define IDC_AXIS_SERIES                 1028
#define IDC_FONTUNDERLINE_CHECK         1028
#define IDC_SERIES_STATIC               1029
#define IDC_FGCOLOR_STATIC              1029
#define IDC_BGCOLOR_STATIC              1030
#define IDC_FGCOLOR_COMBO               1031
#define IDC_SERIES_COMBO                1032
#define IDC_BGCOLOR_COMBO               1032
#define IDC_SERIE_TITLE_STATIC          1033
#define IDC_FGCOLOR_BUTTON              1033
#define IDC_SERIE_TITLE_EDIT            1034
#define IDC_BGCOLOR_BUTTON              1034
#define IDC_LEGEND_CHECK                1035
#define IDC_COLOR_STATIC                1036
#define IDC_COLOR_COMBO                 1037
#define IDC_COLOR_BUTTON                1038
#define IDC_MARKER_STATIC               1039
#define IDC_TITLE_FONTSIZE_COMBO        1039
#define IDC_MARKER_COMBO                1040
#define IDC_LEGEND_FONTSIZE_COMBO       1040
#define IDC_MAKER_SIZE_STATIC           1041
#define IDC_MARKER_SIZE_EDIT            1042
#define IDC_MARKER_CHECK                1043
#define IDC_TRANSP_MARKER_CHECK         1044
#define IDC_DRAW_LEGEND_CHECK           1045
#define IDC_VERTBORDER_STATIC           1049
#define IDC_VERTBORDER_EDIT             1050
#define IDC_HORZBORDER_STATIC           1051
#define IDC_HORZBORDER_EDIT             1052
#define IDC_TITLE_FONTSIZE_STATIC       1053
#define IDC_LEGEND_FONTSIZE_STATIC      1054
#define IDC_TICKWIDTH_EDIT              1055
#define IDC_TICKWIDTH_STATIC            1056
#define ID_START_TRACE                  32771
#define ID_STOP_TRACE                   32772
#define ID_VIEW_LOG                     32773
#define ID_VIEW_MODELSTRUCTURE          32774
#define ID_VIEW_STATUSBAR               32775
#define ID_VIEW_TREE                    32776
#define ID_VIEW_OPTIONS                 32777
#define ID_VIEW_TRACE_TOOLBAR           32782
#define ID_VIEW_LOG_TOOLBAR             32783
#define ID_CHART_NEW                    32784
#define ID_CHART_ADDTONEWCHART          32785
#define ID_SEARCH_FIND                  32787
#define ID_SEARCH_FIND_NEXT             32788
#define ID_SEARCH_FIND_PREVIOUS         32789
#define ID_HELP_KEYWORD                 32790
#define ID_CHART_TIMEWRAP               32791
#define ID_CHART_OPTIONS                32792
#define ID_VIEW_ZOOMIN                  32793
#define ID_VIEW_ZOOMOUT                 32794
#define ID_VIEW_ZOOMAUTO                32795
#define ID_VIEW_ZOOMRESET               32796
#define ID_CHART_FINDINCHARTS           32797
#define ID_VIEW_ZOOM_TOOLBAR            32798
#define ID_SM_NOSHOW                    32802
#define ID_SM_ANIMATION                 32803
#define ID_SM_MONITOR                   32804
#define ID_MODEL_SHOWRATE_INC           32805
#define ID_MODEL_SHOWRATE_INCFOUR       32806
#define ID_MODEL_SHOWRATE_DECFOUR       32807
#define ID_MODEL_SHOWRATE_DEC           32808
#define ID_TRACE_DELAY_INC              32811
#define ID_TRACE_DELAY_INCFOUR          32812
#define ID_TRACE_DELAY_DECFOUR          32813
#define ID_TRACE_DELAY_DEC              32814
#define ID_OPTIONS                      40012
#define IDS_COLORSTYLE_LOG_ES           40114
#define IDS_COLORSTYLE_LOG_EB           40115
#define IDS_COLORSTYLE_LOG_EF           40116
#define IDS_COLORSTYLE_LOG_EI           40117
#define IDS_COLORSTYLE_LOG_ER           40118
#define IDS_COLORSTYLE_LOG_RC           40119
#define IDS_COLORSTYLE_LOG_RE           40120
#define IDS_COLORSTYLE_LOG_RK           40121
#define IDS_COLORSTYLE_LOG_V            40122
#define IDS_COLORSTYLE_LOG_STATUS       40123
#define IDS_COLORSTYLE_LOG_DPS          40124
#define IDS_COLORSTYLE_LOG_SB           40125
#define IDS_COLORSTYLE_LOG_SO           40126
#define IDS_COLORSTYLE_LOG_STN          40127
#define IDS_COLORSTYLE_LOG_STD          40128
#define IDS_COLORSTYLE_LOG_STR          40129
#define IDS_COLORSTYLE_LOG_SRC          40130
#define IDS_COLORSTYLE_LOG_SRE          40131
#define IDS_COLORSTYLE_LOG_SRK          40132
#define IDS_COLORSTYLE_LOG_SD           40133
#define IDS_COLORSTYLE_LOG_SES          40134
#define IDS_COLORSTYLE_LOG_SEN          40135
#define IDS_COLORSTYLE_LOG_SEM          40136
#define IDS_COLORSTYLE_LOG_SEF          40137
#define IDS_COLORSTYLE_LOG_SEU          40138
#define IDS_COLORSTYLE_CHART_AXIS       40139
#define IDS_COLORSTYLE_CHART_TITLE      40140
#define IDS_COLORSTYLE_CHART_LEGEND     40141
#define IDS_COLORSTYLE_CHART_CHART      40142
#define IDS_COLORSTYLE_CHART_TIME       40143
#define IDS_COLORSTYLE_LOG              40150
#define IDS_COLORSTYLE_CHART            40153
#define IDS_COLORSTYLE_LOG_SAMPLE       40160
#define IDS_COLORSTYLE_CHART_SAMPLE1    40166
#define IDS_COLORSTYLE_CHART_SAMPLE2    40167
#define IDS_COLORSTYLE_EDITOR_THEME_CURRENT 40168
#define IDS_COLORSTYLE_EDITOR_THEME_DEFAULT 40169
#define ID_DELAY_STATUSBAR              57635
#define IDS_DELAY_STRING                57636
#define IDS_UEOLEXCEPTION               57637
#define IDS_RESPARAMEXCEPTION           57638
#define IDS_RESOURCEEXCEPTION           57639
#define IDS_RESSTATECHANGEERROR         57639
#define IDS_TRACEEXCEPTION              57640
#define IDS_FILEREADEREXCEPTION         57641
#define IDS_RESCANNOTFIND               57642
#define IDS_RESELIMERROR                57643
#define IDS_RESCREATEERROR              57644
#define IDS_RESULTCANNOTFIND            57645
#define IDS_RESULTVALCHANGEERROR        57646
#define IDS_CANNOTFINDRESTYPE           57647
#define IDS_OPCANNOTFIND                57648
#define IDS_OPSTARTERROR                57649
#define IDS_OPENDERROR                  57650
#define IDS_IECANNOTFIND                57651
#define IDS_IETRACINGERROR              57652
#define IDS_RULETRACINGERROR            57653

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
