// config-tiles.h.  Generated by cmake from config-tiles.h.cmake 

#ifndef __CONFIG_TILES_H_
#define __CONFIG_TILES_H_

#define resource_directory "${CMAKE_CURRENT_SOURCE_DIR}/"
#define test_file_name "test.h" 

#endif /* __CONFIG_TILES_H_ */
