//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by rdo_tracer.rc
//
#define IDS_CAPTION                     1
#define ID_MODEL_START                  2
#define ID_RESOURCE_TYPES               3
#define ID_RESULTS                      4
#define ID_MODEL                        5
#define IDS_LOGSTYLE_ES                 6
#define IDS_LOGSTYLE_EB                 7
#define IDS_LOGSTYLE_EF                 8
#define IDS_LOGSTYLE_EI                 9
#define IDS_LOGSTYLE_ER                 10
#define IDS_LOGSTYLE_RC                 11
#define IDS_LOGSTYLE_RE                 12
#define IDS_LOGSTYLE_RK                 13
#define IDS_LOGSTYLE_V                  14
#define IDS_LOGSTYLE_S                  15
#define IDS_LOGSTYLE_DPS                16
#define IDS_LOGSTYLE_SB                 17
#define IDS_LOGSTYLE_SO                 18
#define IDS_LOGSTYLE_STN                19
#define IDS_LOGSTYLE_STD                20
#define IDS_LOGSTYLE_STR                21
#define IDS_LOGSTYLE_SRC                22
#define IDS_LOGSTYLE_SRE                23
#define IDS_LOGSTYLE_SRK                24
#define IDS_LOGSTYLE_SD                 25
#define IDS_LOGSTYLE_SES                26
#define IDS_LOGSTYLE_SEN                27
#define IDS_LOGSTYLE_SEM                28
#define IDS_LOGSTYLE_SEF                29
#define IDS_LOGSTYLE_SEU                30
#define IDS_OPTIONS                     31
#define IDS_LOG_SAMPLE                  32
#define IDS_TRACE_TOOLBAR               33
#define IDS_LOG_TOOLBAR                 34
#define ID_MSG_CANTFIND                 35
#define ID_PATTERNS                     36
#define ID_RAO_CLIPBRD                  37
#define ID_COORD_STATUSBAR              38
#define ID_MODIFY_STATUSBAR             39
#define IDS_CHART_TITLE                 41
#define IDS_CHART_OPTIONS_APPLY         42
#define IDS_CHART_OPTIONS               43
#define IDS_TRACE_FILTER                44
#define IDS_ZOOM_TOOLBAR                45
#define IDR_MAINFRAME                   128
#define ID_MSG_NO_HELP_FILE             129
#define IDB_TREECTRL                    130
#define ID_STATUSBAR_READONLY           130
#define IDR_TRACE_TOOLBAR               134
#define IDB_TRACE_TOOLBAR_D             136
#define IDR_LOG_TOOLBAR                 137
#define IDB_LOG_TOOLBAR_D               139
#define IDD_CHART_OPTIONS_CHART         140
#define IDD_CHART_OPTIONS_SERIES        141
#define IDR_ZOOM_TOOLBAR                145
#define IDB_ZOOM_TOOLBAR_D              147
#define IDC_CHART_TITLE_STATIC          1021
#define IDC_CHART_TITLE_EDIT            1022
#define IDC_VAL_COUNT_Y_STATIC          1023
#define IDC_IDC_VAL_COUNT_Y_EDIT        1024
#define IDC_VAL_COUNT_X_STATIC          1025
#define IDC_IDC_VAL_COUNT_X_EDIT        1026
#define IDC_AXIS_VAL_STATIC             1027
#define IDC_AXIS_SERIES                 1028
#define IDC_SERIES_STATIC               1029
#define IDC_SERIES_COMBO                1032
#define IDC_SERIE_TITLE_STATIC          1033
#define IDC_SERIE_TITLE_EDIT            1034
#define IDC_LEGEND_CHECK                1035
#define IDC_COLOR_STATIC                1036
#define IDC_COLOR_COMBO                 1037
#define IDC_COLOR_BUTTON                1038
#define IDC_MARKER_STATIC               1039
#define IDC_MARKER_COMBO                1040
#define IDC_MAKER_SIZE_STATIC           1041
#define IDC_MARKER_SIZE_EDIT            1042
#define IDC_MARKER_CHECK                1043
#define IDC_TRANSP_MARKER_CHECK         1044
#define IDC_DRAW_LEGEND_CHECK           1045
#define ID_START_TRACE                  32771
#define ID_STOP_TRACE                   32772
#define ID_VIEW_LOG                     32773
#define ID_VIEW_MODELSTRUCTURE          32774
#define ID_VIEW_STATUSBAR               32775
#define ID_VIEW_TREE                    32776
#define ID_VIEW_OPTIONS                 32777
#define ID_VIEW_TRACE_TOOLBAR           32782
#define ID_VIEW_LOG_TOOLBAR             32783
#define ID_CHART_NEW                    32784
#define ID_CHART_ADDTONEWCHART          32785
#define ID_SEARCH_FIND                  32787
#define ID_SEARCH_FIND_NEXT             32788
#define ID_SEARCH_FIND_PREVIOUS         32789
#define ID_HELP_KEYWORD                 32790
#define ID_CHART_TIMEWRAP               32791
#define ID_CHART_OPTIONS                32792
#define ID_VIEW_ZOOMIN                  32793
#define ID_VIEW_ZOOMOUT                 32794
#define ID_VIEW_ZOOMAUTO                32795
#define ID_VIEW_ZOOMRESET               32796
#define ID_CHART_FINDINCHARTS           32797
#define ID_VIEW_ZOOM_TOOLBAR            32798
#define ID_SM_NOSHOW                    32802
#define ID_SM_ANIMATION                 32803
#define ID_SM_MONITOR                   32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
