QStringList insertMenu;

insertMenu.push_back("INSERT_PAT_TEMPL_OPERATION   | PAT operation       ");
insertMenu.push_back("INSERT_PAT_TEMPL_EVENT       | PAT event           ");
insertMenu.push_back("INSERT_PAT_TEMPL_RULE        | PAT rule            ");
insertMenu.push_back("INSERT_PAT_TEMPL_KEYBOARD    | PAT keyboard        ");
insertMenu.push_back("INSERT_PAT_PATTERN           | $Pattern            ");
insertMenu.push_back("INSERT_PAT_OPERATION         | operation           ");
insertMenu.push_back("INSERT_PAT_EVENT             | event               ");
insertMenu.push_back("INSERT_PAT_RULE              | rule                ");
insertMenu.push_back("INSERT_PAT_KEYBOARD          | keyboard            ");
insertMenu.push_back("INSERT_PAT_TRACE             | trace               ");
insertMenu.push_back("INSERT_PAT_NOTRACE           | no_trace            ");
insertMenu.push_back("INSERT_PAT_PARAMETERS        | $Parameters         ");
insertMenu.push_back("INSERT_PAT_RELEVANTRESOURCES | $Relevant_resources ");
insertMenu.push_back("INSERT_PAT_KEEP              | Keep                ");
insertMenu.push_back("INSERT_PAT_NOCHANGE          | NoChange            ");
insertMenu.push_back("INSERT_PAT_CREATE            | Create              ");
insertMenu.push_back("INSERT_PAT_ERASE             | Erase               ");
insertMenu.push_back("INSERT_PAT_NONEXIST          | NonExist            ");
insertMenu.push_back("INSERT_PAT_TIME              | $Time               ");
insertMenu.push_back("INSERT_PAT_BODY              | $Body               ");
insertMenu.push_back("INSERT_PAT_CONVERTBEGIN      | Convert_begin       ");
insertMenu.push_back("INSERT_PAT_CONVERTEND        | Convert_end         ");
insertMenu.push_back("INSERT_PAT_CONVERTEVENT      | Convert_event       ");
insertMenu.push_back("INSERT_PAT_CONVERTRULE       | Convert_rule        ");
insertMenu.push_back("INSERT_PAT_CHOICEFROM        | Convert_from        ");
insertMenu.push_back("INSERT_PAT_CHOICENOCHECK     | Choise NoCheck      ");
insertMenu.push_back("INSERT_PAT_FIRST             | first               ");
insertMenu.push_back("INSERT_PAT_WITHMAX           | with_max            ");
insertMenu.push_back("INSERT_PAT_WITHMIN           | with_min            ");
insertMenu.push_back("INSERT_PAT_SET               | set                 ");
insertMenu.push_back("INSERT_PAT_END               | $End                ");

insertMenu.push_back("INSERT_PAT_TEMPL_EVENT               | EVN                 ");
insertMenu.push_back("INSERT_PAT_PATTERN                   | $Pattern            ");
insertMenu.push_back("INSERT_PAT_TRACE                     | trace               ");
insertMenu.push_back("INSERT_PAT_NOTRACE                   | no trace            ");
insertMenu.push_back("INSERT_PAT_PARAMETERS                | $Parameters         ");
insertMenu.push_back("INSERT_PAT_RELEVANTRESOURCES         | $Relevant_resources ");
insertMenu.push_back("INSERT_PAT_KEEP                      | Keep                ");
insertMenu.push_back("INSERT_PAT_NOCHANGEINSERT_PAT_CREATE | NoChange            ");
insertMenu.push_back("INSERT_PAT_CREATE                    | Create              ");
insertMenu.push_back("INSERT_PAT_ERASE                     | Erase               ");
insertMenu.push_back("INSERT_PAT_NONEXIST                  | NonExist            ");
insertMenu.push_back("INSERT_PAT_BODY                      | $Body               ");
insertMenu.push_back("INSERT_PAT_CONVERTEVENT              | Convert_event       ");
insertMenu.push_back("INSERT_PAT_END                       | $End                ");

insertMenu.push_back("INSERT_PRC_TEMPL_PROCESS | $Process  ");
insertMenu.push_back("INSERT_PRC_GENERATE      | GENERATE  ");
insertMenu.push_back("INSERT_PRC_SEIZE         | SEIZE     ");
insertMenu.push_back("INSERT_PRC_RELEASE       | RELEASE   ");
insertMenu.push_back("INSERT_PRC_ADVANCE       | ADVANCE   ");
insertMenu.push_back("INSERT_PRC_QUEUE         | QUEUE     ");
insertMenu.push_back("INSERT_PRC_DEPART        | DEPART    ");
insertMenu.push_back("INSERT_PRC_ASSIGN        | ASSIGN    ");
insertMenu.push_back("INSERT_PRC_TERMINATE     | TERMINATE ");

insertMenu.push_back("INSERT_RTP_RTPPERMANENT     | RTP permanent     ");
insertMenu.push_back("INSERT_RTP_RTPTEMPORARY     | PTR temporary     ");
insertMenu.push_back("INSERT_RTP_RESOURCETYPE     | $Resource_type    ");
insertMenu.push_back("INSERT_RTP_PERMANENT        | permament         ");
insertMenu.push_back("INSERT_RTP_TEMPORARY        | temprorary        ");
insertMenu.push_back("INSERT_RTP_PARAMETERS       | $Parameters       ");
insertMenu.push_back("INSERT_RTP_FUZZY_PARAMETERS | $Fuzzy parameters ");
insertMenu.push_back("INSERT_RTP_FUZZY_TERM       | Term              ");
insertMenu.push_back("INSERT_RTP_INTEGER          | integer           ");
insertMenu.push_back("INSERT_RTP_LONGINT          | longint           ");
insertMenu.push_back("INSERT_RTP_REAL             | real              ");
insertMenu.push_back("INSERT_RTP_ENUM             | enum              ");
insertMenu.push_back("INSERT_RTP_STRING           | string            ");
insertMenu.push_back("INSERT_RTP_BOOL             | bool              ");
insertMenu.push_back("INSERT_RTP_TRUE             | true              ");
insertMenu.push_back("INSERT_RTP_FALSE            | false             ");
insertMenu.push_back("INSERT_RTP_SUCHAS           | such_as           ");
insertMenu.push_back("INSERT_RTP_END              | $End              ");

insertMenu.push_back("INSERT_RSS_RSS              | RSS        ");
insertMenu.push_back("INSERT_RSS_RESOURCES        | $Resources ");
insertMenu.push_back("INSERT_RSS_TRACE            | trace      ");
insertMenu.push_back("INSERT_RSS_NOTRACE          | no_trace   ");
insertMenu.push_back("INSERT_RSS_END              | $End       ");

insertMenu.push_back("INSERT_FRM_FRM         | FRM           ");
insertMenu.push_back("INSERT_FRM_FRAME       | $Frame        ");
insertMenu.push_back("INSERT_FRM_BACKPICTURE | $Back_picture ");
insertMenu.push_back("INSERT_FRM_SHOW        | Show          ");
insertMenu.push_back("INSERT_FRM_SHOWIF      | Show_if       ");
insertMenu.push_back("INSERT_FRM_BITMAP      | bitmap        ");
insertMenu.push_back("INSERT_FRM_TEXT        | text          ");
insertMenu.push_back("INSERT_FRM_LINE        | line          ");
insertMenu.push_back("INSERT_FRM_RECT        | rect          ");
insertMenu.push_back("INSERT_FRM_CIRCLE      | circle        ");
insertMenu.push_back("INSERT_FRM_ELLIPSE     | ellipse       ");
insertMenu.push_back("INSERT_FRM_RRECT       | r_rect        ");
insertMenu.push_back("INSERT_FRM_TRIANG      | triang        ");
insertMenu.push_back("INSERT_FRM_SBMP        | s_bmp         ");
insertMenu.push_back("INSERT_FRM_ACTIVE      | active        ");
insertMenu.push_back("INSERT_FRM_END         | $End          ");

insertMenu.push_back("INSERT_FUN_FUN         | FUN         ");
insertMenu.push_back("INSERT_FUN_SQN         | SQN         ");
insertMenu.push_back("INSERT_FUN_CNS         | CNS         ");
insertMenu.push_back("INSERT_FUN_FUNCTION    | $Function   ");
insertMenu.push_back("INSERT_FUN_TYPE        | $Type       ");
insertMenu.push_back("INSERT_FUN_ALGORITHMIC | algorithmic ");
insertMenu.push_back("INSERT_FUN_LIST        | list        ");
insertMenu.push_back("INSERT_FUN_TABLE       | table       ");
insertMenu.push_back("INSERT_FUN_NORMAL      | normal      ");
insertMenu.push_back("INSERT_FUN_UNIFORM     | uniform     ");
insertMenu.push_back("INSERT_FUN_EXPONENTIAL | exponential ");
insertMenu.push_back("INSERT_FUN_TRIANGULAR  | triangular  ");
insertMenu.push_back("INSERT_FUN_BYHIST      | by_hist     ");
insertMenu.push_back("INSERT_FUN_ENUMERATIVE | enumerative ");
insertMenu.push_back("INSERT_FUN_PARAMETERS  | $Parameters ");
insertMenu.push_back("INSERT_FUN_BODY        | $Body       ");
insertMenu.push_back("INSERT_FUN_SEQUENCE    | $Sequence   ");
insertMenu.push_back("INSERT_FUN_CONSTANT    | $Constant   ");
insertMenu.push_back("INSERT_FUN_END         | $End        ");

insertMenu.push_back("INSERT_DPT_TEMPL_SEARCH   | DPT search      ");
insertMenu.push_back("INSERT_DPT_TEMPL_PRIOR    | DPT prior       ");
insertMenu.push_back("INSERT_DPT_TEMPL_SOME     | DPT some        ");
insertMenu.push_back("INSERT_DPT_ACTIV          | ACTIV           ");
insertMenu.push_back("INSERT_DPT_DECISIONPOINT  | $Decision_point ");
insertMenu.push_back("INSERT_DPT_SOME           | some            ");
insertMenu.push_back("INSERT_DPT_SEARCH         | search          ");
insertMenu.push_back("INSERT_DPT_PRIOR          | prior           ");
insertMenu.push_back("INSERT_DPT_NOTRACE        | no_trace        ");
insertMenu.push_back("INSERT_DPT_TRACESTAT      | trace_stat      ");
insertMenu.push_back("INSERT_DPT_TRACETOPS      | trace_tops      ");
insertMenu.push_back("INSERT_DPT_TRACEALL       | trace_all       ");
insertMenu.push_back("INSERT_DPT_CONDITION      | $Condition      ");
insertMenu.push_back("INSERT_DPT_TERMCONDITION  | $Term_condition ");
insertMenu.push_back("INSERT_DPT_EVALUATEBY     | $Evaluate_by    ");
insertMenu.push_back("INSERT_DPT_COMPARETOPS    | $Compare_tops   ");
insertMenu.push_back("INSERT_DPT_MULTITHREADING | $Multithreading ");
insertMenu.push_back("INSERT_DPT_YES            | YES             ");
insertMenu.push_back("INSERT_DPT_NO             | NO              ");
insertMenu.push_back("INSERT_DPT_ACTIVITIES     | $Activities     ");
insertMenu.push_back("INSERT_DPT_VALUEBEFORE    | value before    ");
insertMenu.push_back("INSERT_DPT_VALUEAFTER     | value after     ");
insertMenu.push_back("INSERT_DPT_END            | $End            ");

insertMenu.push_back("INSERT_SMR_OPERATION      | SMR             ");
insertMenu.push_back("INSERT_SMR_MODELNAME      | Model_name      ");
insertMenu.push_back("INSERT_SMR_RESOURCEFILE   | Resource_file   ");
insertMenu.push_back("INSERT_SMR_OPRIEVFILE     | OprIev_file     ");
insertMenu.push_back("INSERT_SMR_STATISTICFILE  | Statistics_file ");
insertMenu.push_back("INSERT_SMR_RESULTSFILE    | Results_file    ");
insertMenu.push_back("INSERT_SMR_TRACEFILE      | Trace_file      ");
insertMenu.push_back("INSERT_SMR_FRAMEFILE      | Frame_file      ");
insertMenu.push_back("INSERT_SMR_FRAMENUMBER    | Frame_number    ");
insertMenu.push_back("INSERT_SMR_SHOWMODE       | Show_mode       ");
insertMenu.push_back("INSERT_SMR_ANIMATION      | Animation       ");
insertMenu.push_back("INSERT_SMR_MONITOR        | Monitor         ");
insertMenu.push_back("INSERT_SMR_NOSHOW         | NoShow          ");
insertMenu.push_back("INSERT_SMR_SHOWRATE       | Show_rate       ");
insertMenu.push_back("INSERT_SMR_RUNSTARTTIME   | Run_StartTime   ");
insertMenu.push_back("INSERT_SMR_TRACESTARTTIME | Trace_StartTime ");
insertMenu.push_back("INSERT_SMR_TRACEENDTIME   | Trace_EndTime   ");
insertMenu.push_back("INSERT_SMR_TERMINATEIF    | Terminate_if    ");
insertMenu.push_back("INSERT_SMR_TIMENOW        | Time_now        ");
insertMenu.push_back("INSERT_SMR_SECONDS        | Seconds         ");
insertMenu.push_back("INSERT_SMR_BREAKPOINT     | Break_point     ");
insertMenu.push_back("INSERT_SMR_INCLUDE        | $Include        ");

insertMenu.push_back("INSERT_PMD_PMD        | PMD         ");
insertMenu.push_back("INSERT_PMD_RESULTS    | $Results    ");
insertMenu.push_back("INSERT_PMD_WATCHPAR   | watch_par   ");
insertMenu.push_back("INSERT_PMD_WATCHSTATE | watch_state ");
insertMenu.push_back("INSERT_PMD_WATCHQUANT | watch_quant ");
insertMenu.push_back("INSERT_PMD_WATCHVALUE | watch_value ");
insertMenu.push_back("INSERT_PMD_GETVALUE   | get_value   ");
insertMenu.push_back("INSERT_PMD_TRACE      | trace       ");
insertMenu.push_back("INSERT_PMD_NOTRACE    | no_trace    ");
insertMenu.push_back("INSERT_PMD_END        | $End        ");

insertMenu.push_back("LINE");

insertMenu.push_back("INSERT_ALGO_IF      | if      ");
insertMenu.push_back("INSERT_ALGO_ELSE    | else    ");
insertMenu.push_back("INSERT_ALGO_IF_ELSE | if-else ");
insertMenu.push_back("INSERT_ALGO_FOR     | for     ");
insertMenu.push_back("INSERT_ALGO_RETURN  | return  ");

insertMenu.push_back("INSERT_FUNCTIONS_ABS             | Abs             ");
insertMenu.push_back("INSERT_FUNCTIONS_ARCCOS          | ArcCos          ");
insertMenu.push_back("INSERT_FUNCTIONS_ARCSIN          | ArcSin          ");
insertMenu.push_back("INSERT_FUNCTIONS_ARCTAN          | ArcTan          ");
insertMenu.push_back("INSERT_FUNCTIONS_COS             | Cos             ");
insertMenu.push_back("INSERT_FUNCTIONS_COTAN           | Cotan           ");
insertMenu.push_back("INSERT_FUNCTIONS_EXIST           | Exist           ");
insertMenu.push_back("INSERT_FUNCTIONS_EXP             | Exp             ");
insertMenu.push_back("INSERT_FUNCTIONS_FLOOR           | Floor           ");
insertMenu.push_back("INSERT_FUNCTIONS_FOR_ALL         | For_All         ");
insertMenu.push_back("INSERT_FUNCTIONS_FRAC            | Frac            ");
insertMenu.push_back("INSERT_FUNCTIONS_GETRELRESNUMBER | GetRelResNumber ");
insertMenu.push_back("INSERT_FUNCTIONS_GETRESNUMBER    | GetResNumber    ");
insertMenu.push_back("INSERT_FUNCTIONS_IABS            | IAbs            ");
insertMenu.push_back("INSERT_FUNCTIONS_IMAX            | IMax            ");
insertMenu.push_back("INSERT_FUNCTIONS_IMIN            | IMin            ");
insertMenu.push_back("INSERT_FUNCTIONS_INT             | Int             ");
insertMenu.push_back("INSERT_FUNCTIONS_INTPOWER        | IntPower        ");
insertMenu.push_back("INSERT_FUNCTIONS_LN              | Ln              ");
insertMenu.push_back("INSERT_FUNCTIONS_LOG2            | Log10           ");
insertMenu.push_back("INSERT_FUNCTIONS_LOG10           | Log2            ");

insertMenu.push_back("LINE");