//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by chat.rc
//
#define IDR_MAINFRAME                   128
#define IDR_STATUSMODE_TOOLBAR          128
#define IDB_STATUSMODE                  131
#define IDD_OPTIONS_GENERAL_DIALOG      136
#define IDR_INCOMINGMESSAGE_WAVE        142
#define IDR_CHATRET_WAVE                147
#define IDR_CHATTYPE_WAVE               148
#define IDR_CHATBACK_WAVE               149
#define IDR_CONNECT_WAVE                151
#define IDR_DISCONNECT_WAVE             152
#define IDR_CHANGESTATUSMODE_WAVE       153
#define IDI_TRAY_APP                    156
#define IDI_TRAY_MESSAGE                157
#define IDR_TRAY_MENU                   159
#define IDD_OPTIONS_SOUND_DIALOG        163
#define IDB_SOUND                       164
#define IDD_POPUP_DIALOG                168
#define IDD_OPTIONS_STATUSMODE_DIALOG   170
#define IDD_STATUSMODEINFO_DIALOG       171
#define IDD_TOCRYOUT_DIALOG             173
#define IDC_USERNAME_EDIT               1000
#define IDC_USERNAME_STATIC             1001
#define IDC_USER_GROUPBOX               1003
#define IDC_CLOSEBUTTON_GROUPBOX        1004
#define IDC_CLOSEBUTTON_CLOSE_RADIO     1005
#define IDC_CLOSEBUTTON_MINIMIZE_RADIO  1006
#define IDC_CLOSEBUTTON_TRAY_RADIO      1007
#define IDC_MINIMIZEBUTTON_MINIMIZE_RADIO 1008
#define IDC_MINIMIZEBUTTON_TRAY_RADIO   1009
#define IDC_MINIMIZEBUTTON_GROUPBOX     1010
#define IDC_TRAYUSE_CHECK               1011
#define IDC_TRAYNOTIFY_CHECK            1012
#define IDC_TRAY_GROUPBOX               1013
#define IDC_SOUNDUSE_CHECK              1014
#define IDC_SOUND_LIST                  1015
#define IDC_SOUNDDEFAULT_RADIO          1016
#define IDC_SOUNDEXTERNAL_RADIO         1017
#define IDC_SOUNDNONE_RADIO             1018
#define IDC_SOUNDEXTERNAL_EDIT          1019
#define IDC_SOUNDEXTERMAL_BUTTON        1020
#define IDC_POPUPUSE_CHECK              1021
#define IDC_POPUPPOSITION_COMBO         1022
#define IDC_POPUPDELAY_SPIN             1023
#define IDC_POPUPDELAY_EDIT             1024
#define IDC_POPUPTEXTCOLOR_COMBO        1026
#define IDC_POPUPBACKGROUNDCOLOR_COMBO  1027
#define IDC_POPUP_GROUPBOX              1028
#define IDC_POPUPPOSITION_STATIC        1029
#define IDC_POPUPDELAY_STATIC           1030
#define IDC_POPUPTEXTCOLOR_STATIC       1031
#define IDC_POPUPTEXTCOLOR_BUTTON       1032
#define IDC_POPUPBACKGROUNDCOLOR_BUTTON 1033
#define IDC_POPUPBACKGROUNDCOLOR_STATIC 1034
#define IDC_STATUSMODE_LIST             1035
#define IDC_STATUSMODENAME_EDIT         1036
#define IDC_STATUSMODEINFO_EDIT         1037
#define IDC_STATUSMODENAME_STATIC       1038
#define IDC_STATUSMODEINFO_STATIC       1039
#define IDC_INFO_EDIT                   1040
#define IDC_INFO_STATIC                 1041
#define IDC_INFO_CHECK                  1042
#define IDC_AUTOMATICALLYSTATUSMODE_STATIC 1046
#define IDC_AUTOMATICALLYSTATUSMODE_AWAY_CHECK 1047
#define IDC_AUTOMATICALLYSTATUSMODE_AWAY_EDIT 1048
#define IDC_AUTOMATICALLYSTATUSMODE_AWAY_SPIN 1049
#define IDC_AUTOMATICALLYSTATUSMODE_AWAY_STATIC 1050
#define IDC_AUTOMATICALLYSTATUSMODE_NOTAVAILIBLE_CHECK 1051
#define IDC_AUTOMATICALLYSTATUSMODE_NOTAVAILIBLE_EDIT 1052
#define IDC_TOCRYOUT_EDIT               1052
#define IDC_AUTOMATICALLYSTATUSMODE_NOTAVAILIBLE_SPIN 1053
#define IDC_AUTOMATICALLYSTATUSMODE_NOTAVAILIBLE_STATIC 1054
#define ID_STATUSMODE_ONLINE            32773
#define ID_STATUSMODE_AWAY              32776
#define ID_STATUSMODE_NOTAVAILIBLE      32778
#define ID_TRAYMENU_OPEN                32782
#define ID_TRAYMENU_EXIT                32783
#define ID_CHAT_TOCRYOUT                32793
#define ID_FILE_REFRESHUSERSLIST        32794
#define ID_STATUSMODE_ONLINE_INFO       32795
#define ID_STATUSMODE_AWAY_INFO         32796
#define ID_STATUSMODE_NOTAVAILIBLE_INFO 32797
#define ID_CHAT_OPTIONS                 32798
#define ID_INFOSTATUSBAR                59394
#define ID_STATUSMODE_TOOLBAR           61204
#define ID_OPTIONS                      61205
#define ID_CONNECT_WAVE                 61206
#define ID_DISCONNECT_WAVE              61207
#define ID_CHANGESTATUSMODE_WAVE        61208
#define ID_INCOMINGMESSAGE_WAVE         61209
#define ID_CHATTYPE_WAVE                61210
#define ID_CHATBACK_WAVE                61211
#define ID_CHATRET_WAVE                 61212
#define IDS_STATUSMODE_ONLINE           61213
#define IDS_STATUSMODE_AWAY             61214
#define IDS_STATUSMODE_NOTAVAILIBLE     61215
#define IDS_STATUSMODE_VIEWERLOG        61216
#define IDS_STATUSMODEWITHINFO_VIEWERLOG 61217
#define IDS_CONNECT_VIEWERLOG           61218
#define IDS_DISCONNECT_VIEWERLOG        61219
#define IDS_STATUSMODE_CHANGEAUTOMATICALLY 61220

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        176
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
