//---------------------------------------------------------------------------
#ifndef ConstRes_UnitH
#define ConstRes_UnitH
//---------------------------------------------------------------------------
#define StringID                       5000
#define sAppTitle                      0 + StringID
#define sCaption                       1 + StringID
#define sRecordDelete                  2 + StringID
#define sSelectProgramm                3 + StringID
#define sCompanyName                   4 + StringID
#define sProgramCreate                 5 + StringID
#define sProgramDelete                 6 + StringID
#define sUnknowValue                   7 + StringID
#define sUnknowDate                    8 + StringID
#define sDateMask                      9 + StringID
#define sHaveProgramByDate            10 + StringID
#define sNoProgramByDate              11 + StringID
#define sYesValueUpperCase            12 + StringID
#define sNoValueLowerCase             13 + StringID
#define sMainProgramPart              14 + StringID
#define sNotMainProgramPart           15 + StringID
#define sMainProgramPart_short        16 + StringID
#define sNotMainProgramPart_short     17 + StringID
#define sMainProgramPartComplete      18 + StringID
#define sNotMainProgramPartComplete   19 + StringID
#define sProgramPartDelete            20 + StringID
#define sProgramPartLock              21 + StringID
#define sIniFileName                  22 + StringID
#define sFindProductName              23 + StringID
#define StringID_End                  sFindProductName

#define ErrorID                              StringID_End + 1
#define sUnknownError                        0 + ErrorID
#define sFunError                            1 + ErrorID
#define sErrorFolderBrowse                   2 + ErrorID
#define sErrorDeletePersonal                 3 + ErrorID
#define sErrorDeleteMachine                  4 + ErrorID
#define sErrorBuildDailyTasks                5 + ErrorID
#define sErrorBuildModel                     6 + ErrorID
#define sErrorRDORun                         7 + ErrorID
#define sErrorCreateProcess                  8 + ErrorID
#define sErrorBuildModelData                 9 + ErrorID
#define sErrorOpenTraceFile                 10 + ErrorID
#define sErrorNoOrders                      11 + ErrorID
#define sErrorNoMachineInProg               12 + ErrorID
#define sErrorBadMachineInProg              13 + ErrorID
#define sErrorPlaneKoef                     14 + ErrorID
#define sErrorBadMachine                    15 + ErrorID
#define sErrorBadMachinePressure            16 + ErrorID
#define sErrorBadMachineEffort              17 + ErrorID
#define sErrorBadMachineFloors              18 + ErrorID
#define sErrorBadMachineFloorHeight         19 + ErrorID
#define sErrorBadMachineLoadSides           20 + ErrorID
#define sErrorBadMachinePlateLength         21 + ErrorID
#define sErrorBadMachinePlateWidth          22 + ErrorID
#define sErrorBadProduct                    23 + ErrorID
#define sErrorBadProductLoadTime            24 + ErrorID
#define sErrorBadProductVulcanTime          25 + ErrorID
#define sErrorBadProductVulcanTemperature   26 + ErrorID
#define sErrorBadProductPFPressureOn100     27 + ErrorID
#define sErrorBadProductPFNumber            28 + ErrorID
#define sErrorBadProductPFPlaces            29 + ErrorID
#define sErrorBadProductPFHeight            30 + ErrorID
#define sErrorBadProductPFWidth             31 + ErrorID
#define sErrorBadProductPFLength            32 + ErrorID
#define sErrorBadProductPFDiameter          33 + ErrorID
#define ErrorID_End                         sErrorBadProductPFDiameter

#define Translate_ID           ErrorID_End + 1
#define Tr1                    0 + Translate_ID
#define Tr2                    1 + Translate_ID
#define Tr3                    2 + Translate_ID
#define Tr4                    3 + Translate_ID
#define Tr5                    4 + Translate_ID
#define Tr6                    5 + Translate_ID
#define Tr7                    6 + Translate_ID
#define Tr8                    7 + Translate_ID
#define Tr9                    8 + Translate_ID
#define Tr10                   9 + Translate_ID
#define Tr11                  10 + Translate_ID
#define Tr12                  11 + Translate_ID
#define Tr13                  12 + Translate_ID
#define Tr14                  13 + Translate_ID
#define Tr15                  14 + Translate_ID
#define Tr16                  15 + Translate_ID
#define Tr17                  16 + Translate_ID
#define Tr18                  17 + Translate_ID
#define Tr19                  18 + Translate_ID
#define Tr20                  19 + Translate_ID
#define Tr21                  20 + Translate_ID
#define Tr22                  21 + Translate_ID
#define Tr23                  22 + Translate_ID
#define Tr24                  23 + Translate_ID
#define Tr25                  24 + Translate_ID
#define Tr26                  25 + Translate_ID
#define Tr27                  26 + Translate_ID
#define Tr28                  27 + Translate_ID
#define Tr29                  28 + Translate_ID
#define Tr30                  29 + Translate_ID
#define Tr31                  30 + Translate_ID
#define Tr32                  31 + Translate_ID
#define Tr33                  32 + Translate_ID
#define Tr34                  33 + Translate_ID
#define Tr35                  34 + Translate_ID
#define Tr36                  35 + Translate_ID
#define Tr37                  36 + Translate_ID
#define Tr38                  37 + Translate_ID
#define Tr39                  38 + Translate_ID
#define Tr40                  39 + Translate_ID
#define Tr41                  40 + Translate_ID
#define Tr42                  41 + Translate_ID
#define Tr43                  42 + Translate_ID
#define Tr44                  43 + Translate_ID
#define Tr45                  44 + Translate_ID
#define Tr46                  45 + Translate_ID
#define Tr47                  46 + Translate_ID
#define Tr48                  47 + Translate_ID
#define Tr49                  48 + Translate_ID
#define Tr50                  49 + Translate_ID
#define Tr51                  50 + Translate_ID
#define Tr52                  51 + Translate_ID
#define Tr53                  52 + Translate_ID
#define Tr54                  53 + Translate_ID
#define Tr55                  54 + Translate_ID
#define Tr56                  55 + Translate_ID
#define Tr57                  56 + Translate_ID
#define Tr58                  57 + Translate_ID
#define Tr59                  58 + Translate_ID
#define Tr60                  59 + Translate_ID
#define Tr61                  60 + Translate_ID
#define Tr62                  61 + Translate_ID
#define Tr63                  62 + Translate_ID
#define Tr64                  63 + Translate_ID
#define Tr65                  64 + Translate_ID
#define Tr66                  65 + Translate_ID
#define Tr67                  66 + Translate_ID
#define Tr68                  67 + Translate_ID
#define Tr69                  68 + Translate_ID
#define Tr70                  69 + Translate_ID
#define Tr71                  70 + Translate_ID
#define Tr72                  71 + Translate_ID
#define Tr73                  72 + Translate_ID
#define Tr74                  73 + Translate_ID
#define Tr75                  74 + Translate_ID
#define Tr76                  75 + Translate_ID
#define Tr77                  76 + Translate_ID
#define Tr78                  77 + Translate_ID
#define Tr79                  78 + Translate_ID
#define Tr80                  79 + Translate_ID
#define Tr81                  80 + Translate_ID
#define Tr82                  81 + Translate_ID
#define Tr83                  82 + Translate_ID
#define Tr84                  83 + Translate_ID
#define Tr85                  84 + Translate_ID
#define Tr86                  85 + Translate_ID
#define Tr87                  86 + Translate_ID
#define Tr88                  87 + Translate_ID
#define Tr89                  88 + Translate_ID
#define Tr90                  89 + Translate_ID
#define Tr91                  90 + Translate_ID
#define Tr92                  91 + Translate_ID
#define Tr93                  92 + Translate_ID
#define Tr94                  93 + Translate_ID
#define Tr95                  94 + Translate_ID
#define Tr96                  95 + Translate_ID
#define Tr97                  96 + Translate_ID
#define Tr98                  97 + Translate_ID
#define Tr99                  98 + Translate_ID
#define Tr100                 99 + Translate_ID
#define Tr101                100 + Translate_ID
#define Tr102                101 + Translate_ID
#define Tr103                102 + Translate_ID
#define Tr104                103 + Translate_ID
#define Tr105                104 + Translate_ID
#define Tr106                105 + Translate_ID
#define Tr107                106 + Translate_ID
#define Tr108                107 + Translate_ID
#define Tr109                108 + Translate_ID
#define Tr110                109 + Translate_ID

#define Tr111                110 + Translate_ID
#define Tr112                111 + Translate_ID
#define Tr113                112 + Translate_ID
#define Tr114                113 + Translate_ID
#define Tr115                114 + Translate_ID
#define Tr116                115 + Translate_ID
#define Tr117                116 + Translate_ID
#define Tr118                117 + Translate_ID
#define Tr119                118 + Translate_ID
#define Tr120                119 + Translate_ID
#define Tr121                120 + Translate_ID
#define Tr122                121 + Translate_ID
#define Tr123                122 + Translate_ID
#define Tr124                123 + Translate_ID
#define Tr125                124 + Translate_ID
#define Tr126                125 + Translate_ID
#define Tr127                126 + Translate_ID
#define Tr128                127 + Translate_ID
#define Tr129                128 + Translate_ID
#define Tr130                129 + Translate_ID
#define Tr131                130 + Translate_ID
#define Tr132                131 + Translate_ID
#define Tr133                132 + Translate_ID
#define Tr134                133 + Translate_ID
#define Tr135                134 + Translate_ID
#define Tr136                135 + Translate_ID
#define Tr137                136 + Translate_ID
#define Tr138                137 + Translate_ID
#define Tr139                138 + Translate_ID
#define Tr140                139 + Translate_ID
#define Tr141                140 + Translate_ID
#define Tr142                141 + Translate_ID
#define Tr143                142 + Translate_ID
#define Tr144                143 + Translate_ID
#define Tr145                144 + Translate_ID
#define Tr146                145 + Translate_ID
#define Tr147                146 + Translate_ID
#define Tr148                147 + Translate_ID
#define Tr149                148 + Translate_ID
#define Tr150                149 + Translate_ID
#define Tr151                150 + Translate_ID
#define Tr152                151 + Translate_ID
#define Tr153                152 + Translate_ID
#define Tr154                153 + Translate_ID
#define Tr155                154 + Translate_ID
#define Tr156                155 + Translate_ID
#define Tr157                156 + Translate_ID
#define Tr158                157 + Translate_ID
#define Tr159                158 + Translate_ID
#define Tr160                159 + Translate_ID
#define Tr161                160 + Translate_ID
#define Tr162                161 + Translate_ID
#define Tr163                162 + Translate_ID
#define Tr164                163 + Translate_ID
#define Tr165                164 + Translate_ID
#define Tr166                165 + Translate_ID
#define Tr167                166 + Translate_ID
#define Tr168                167 + Translate_ID
#define Tr169                168 + Translate_ID
#define Tr170                169 + Translate_ID
#define Tr171                170 + Translate_ID
#define Tr172                171 + Translate_ID
#define Tr173                172 + Translate_ID
#define Tr174                173 + Translate_ID
#define Tr175                174 + Translate_ID
#define Tr176                175 + Translate_ID
#define Tr177                176 + Translate_ID
#define Tr178                177 + Translate_ID
#define Tr179                178 + Translate_ID
#define Tr180                179 + Translate_ID
#define Tr181                180 + Translate_ID
#define Tr182                181 + Translate_ID
#define Tr183                182 + Translate_ID
#define Tr184                183 + Translate_ID
#define Tr185                184 + Translate_ID
#define Tr186                185 + Translate_ID
#define Tr187                186 + Translate_ID
#define Tr188                187 + Translate_ID
#define Tr189                188 + Translate_ID
#define Tr190                189 + Translate_ID
#define Tr191                190 + Translate_ID
#define Tr192                191 + Translate_ID
#define Tr193                192 + Translate_ID
#define Tr194                193 + Translate_ID
#define Tr195                194 + Translate_ID
#define Tr196                195 + Translate_ID
#define Tr197                196 + Translate_ID
#define Tr198                197 + Translate_ID
#define Tr199                198 + Translate_ID
#define Tr200                199 + Translate_ID
#define Tr201                200 + Translate_ID
#define Tr202                201 + Translate_ID
#define Tr203                202 + Translate_ID
#define Tr204                203 + Translate_ID
#define Tr205                204 + Translate_ID
#define Tr206                205 + Translate_ID
#define Tr207                206 + Translate_ID
#define Tr208                207 + Translate_ID
#define Tr209                208 + Translate_ID
#define Tr210                209 + Translate_ID
#define Tr211                210 + Translate_ID
#define Tr212                211 + Translate_ID
#define Tr213                212 + Translate_ID
#define Tr214                213 + Translate_ID
#define Tr215                214 + Translate_ID
#define Tr216                215 + Translate_ID
#define Tr217                216 + Translate_ID
#define Tr218                217 + Translate_ID
#define Tr219                218 + Translate_ID
#define Tr220                219 + Translate_ID
#define Tr221                220 + Translate_ID
#define Tr222                221 + Translate_ID
#define Tr223                222 + Translate_ID
#define Tr224                223 + Translate_ID
#define Tr225                224 + Translate_ID
#define Tr226                225 + Translate_ID
#define Tr227                226 + Translate_ID
#define Tr228                227 + Translate_ID
#define Tr229                228 + Translate_ID
#define Tr230                229 + Translate_ID
#define Tr231                230 + Translate_ID
#define Tr232                231 + Translate_ID
#define Tr233                232 + Translate_ID
#define Tr234                233 + Translate_ID
#define Tr235                234 + Translate_ID
#define Tr236                235 + Translate_ID
#define Tr237                236 + Translate_ID
#define Tr238                237 + Translate_ID
#define Tr239                238 + Translate_ID
#define Tr240                239 + Translate_ID
#define Tr241                240 + Translate_ID
#define Tr242                241 + Translate_ID
#define Tr243                242 + Translate_ID
#define Tr244                243 + Translate_ID
#define Tr245                244 + Translate_ID
#define Tr246                245 + Translate_ID
#define Tr247                246 + Translate_ID
#define Tr248                247 + Translate_ID

#define Tr249                248 + Translate_ID
#define Tr250                249 + Translate_ID
#define Tr251                250 + Translate_ID
#define Tr252                251 + Translate_ID
#define Tr253                252 + Translate_ID
#define Tr254                253 + Translate_ID
#define Tr255                254 + Translate_ID
#define Tr256                255 + Translate_ID
#define Tr257                256 + Translate_ID
#define Tr258                257 + Translate_ID
#define Translate_ID_End     Tr258

#define Translate_Field_ID        Translate_ID_End + 1
#define Tr_F_1                    0 + Translate_Field_ID
#define Tr_F_2                    1 + Translate_Field_ID
#define Tr_F_3                    2 + Translate_Field_ID
#define Tr_F_4                    3 + Translate_Field_ID
#define Tr_F_5                    4 + Translate_Field_ID
#define Tr_F_6                    5 + Translate_Field_ID
#define Tr_F_7                    6 + Translate_Field_ID
#define Tr_F_8                    7 + Translate_Field_ID
#define Tr_F_9                    8 + Translate_Field_ID
#define Tr_F_10                   9 + Translate_Field_ID
#define Tr_F_11                  10 + Translate_Field_ID
#define Tr_F_12                  11 + Translate_Field_ID
#define Tr_F_13                  12 + Translate_Field_ID
#define Tr_F_14                  13 + Translate_Field_ID
#define Tr_F_15                  14 + Translate_Field_ID
#define Tr_F_16                  15 + Translate_Field_ID
#define Tr_F_17                  16 + Translate_Field_ID
#define Tr_F_18                  17 + Translate_Field_ID
#define Tr_F_19                  18 + Translate_Field_ID
#define Tr_F_20                  19 + Translate_Field_ID
#define Tr_F_21                  20 + Translate_Field_ID
#define Tr_F_22                  21 + Translate_Field_ID
#define Tr_F_23                  22 + Translate_Field_ID
#define Tr_F_24                  23 + Translate_Field_ID
#define Tr_F_25                  24 + Translate_Field_ID
#define Tr_F_26                  25 + Translate_Field_ID
#define Tr_F_27                  26 + Translate_Field_ID
#define Tr_F_28                  27 + Translate_Field_ID
#define Tr_F_29                  28 + Translate_Field_ID
#define Tr_F_30                  29 + Translate_Field_ID
#define Tr_F_31                  30 + Translate_Field_ID
#define Tr_F_32                  31 + Translate_Field_ID
#define Tr_F_33                  32 + Translate_Field_ID
#define Tr_F_34                  33 + Translate_Field_ID
#define Tr_F_35                  34 + Translate_Field_ID
#define Tr_F_36                  35 + Translate_Field_ID
#define Tr_F_37                  36 + Translate_Field_ID
#define Tr_F_38                  37 + Translate_Field_ID
#define Tr_F_39                  38 + Translate_Field_ID
#define Tr_F_40                  39 + Translate_Field_ID
#define Tr_F_41                  40 + Translate_Field_ID
#define Tr_F_42                  41 + Translate_Field_ID
#define Tr_F_43                  42 + Translate_Field_ID
#define Tr_F_44                  43 + Translate_Field_ID
#define Tr_F_45                  44 + Translate_Field_ID
#define Tr_F_46                  45 + Translate_Field_ID
#define Tr_F_47                  46 + Translate_Field_ID
#define Tr_F_48                  47 + Translate_Field_ID
#define Tr_F_49                  48 + Translate_Field_ID
#define Tr_F_50                  49 + Translate_Field_ID
#define Tr_F_51                  50 + Translate_Field_ID
#define Tr_F_52                  51 + Translate_Field_ID
#define Tr_F_53                  52 + Translate_Field_ID
#define Tr_F_54                  53 + Translate_Field_ID
#define Tr_F_55                  54 + Translate_Field_ID
#define Tr_F_56                  55 + Translate_Field_ID
#define Tr_F_57                  56 + Translate_Field_ID
#define Tr_F_58                  57 + Translate_Field_ID
#define Tr_F_59                  58 + Translate_Field_ID
#define Tr_F_60                  59 + Translate_Field_ID
#define Tr_F_61                  60 + Translate_Field_ID
#define Tr_F_62                  61 + Translate_Field_ID
#define Tr_F_63                  62 + Translate_Field_ID
#define Tr_F_64                  63 + Translate_Field_ID
#define Tr_F_65                  64 + Translate_Field_ID
#define Tr_F_66                  65 + Translate_Field_ID
#define Tr_F_67                  66 + Translate_Field_ID
#define Tr_F_68                  67 + Translate_Field_ID
#define Tr_F_69                  68 + Translate_Field_ID
#define Tr_F_70                  69 + Translate_Field_ID
#define Tr_F_71                  70 + Translate_Field_ID
#define Tr_F_72                  71 + Translate_Field_ID
#define Tr_F_73                  72 + Translate_Field_ID
#define Tr_F_74                  73 + Translate_Field_ID
#define Tr_F_75                  74 + Translate_Field_ID
#define Tr_F_76                  75 + Translate_Field_ID
#define Tr_F_77                  76 + Translate_Field_ID
#define Tr_F_78                  77 + Translate_Field_ID
#define Tr_F_79                  78 + Translate_Field_ID
#define Tr_F_80                  79 + Translate_Field_ID
#define Tr_F_81                  80 + Translate_Field_ID
#define Tr_F_82                  81 + Translate_Field_ID
#define Tr_F_83                  82 + Translate_Field_ID
#define Tr_F_84                  83 + Translate_Field_ID
#define Tr_F_85                  84 + Translate_Field_ID
#define Tr_F_86                  85 + Translate_Field_ID
#define Tr_F_87                  86 + Translate_Field_ID
#define Tr_F_88                  87 + Translate_Field_ID
#define Tr_F_89                  88 + Translate_Field_ID
#define Tr_F_90                  89 + Translate_Field_ID
#define Tr_F_91                  90 + Translate_Field_ID
#define Tr_F_92                  91 + Translate_Field_ID
#define Tr_F_93                  92 + Translate_Field_ID
#define Tr_F_94                  93 + Translate_Field_ID
#define Tr_F_95                  94 + Translate_Field_ID
#define Tr_F_96                  95 + Translate_Field_ID
#define Tr_F_97                  96 + Translate_Field_ID
#define Tr_F_98                  97 + Translate_Field_ID
#define Tr_F_99                  98 + Translate_Field_ID
#define Tr_F_100                 99 + Translate_Field_ID
#define Tr_F_101                100 + Translate_Field_ID
#define Tr_F_102                101 + Translate_Field_ID
#define Tr_F_103                102 + Translate_Field_ID
#define Tr_F_104                103 + Translate_Field_ID
#define Tr_F_105                104 + Translate_Field_ID
#define Tr_F_106                105 + Translate_Field_ID
#define Tr_F_107                106 + Translate_Field_ID
#define Tr_F_108                107 + Translate_Field_ID
#define Tr_F_109                108 + Translate_Field_ID
#define Tr_F_110                109 + Translate_Field_ID
#define Tr_F_111                110 + Translate_Field_ID
#define Tr_F_112                111 + Translate_Field_ID
#define Tr_F_113                112 + Translate_Field_ID
#define Tr_F_114                113 + Translate_Field_ID
#define Tr_F_115                114 + Translate_Field_ID
#define Tr_F_116                115 + Translate_Field_ID
#define Tr_F_117                116 + Translate_Field_ID
#define Tr_F_118                117 + Translate_Field_ID
#define Tr_F_119                118 + Translate_Field_ID
#define Tr_F_120                119 + Translate_Field_ID
#define Tr_F_121                120 + Translate_Field_ID
#define Tr_F_122                121 + Translate_Field_ID
#define Translate_Field_ID_End  Tr_F_122

#define RcDataID          1
#define PAT_GEN_MODEL     0 + RcDataID
#define RTP1_GEN_MODEL    1 + RcDataID
#define RTP2_GEN_MODEL    2 + RcDataID
#define RTP3_GEN_MODEL    3 + RcDataID
#define OPR_GEN_MODEL     4 + RcDataID
#define FRM_GEN_MODEL     5 + RcDataID
#define FUN_GEN_MODEL     6 + RcDataID
#define SMR_GEN_MODEL     7 + RcDataID
#define PMD_GEN_MODEL     8 + RcDataID

#define PAT_MODEL         9 + RcDataID
#define RTP1_MODEL       10 + RcDataID
#define RTP2_MODEL       11 + RcDataID
#define RTP3_MODEL       12 + RcDataID
#define OPR_MODEL        13 + RcDataID
#define FRM_MODEL        14 + RcDataID
#define FUN_MODEL        15 + RcDataID
#define SMR_MODEL        16 + RcDataID
#define PMD_MODEL        17 + RcDataID

#define PictureID           100
#define pic_CapRazv         0 + PictureID
//---------------------------------------------------------------------------
#endif

