// Scintilla source code edit control
/** @file SciLexer.h
 ** Interface to the added lexer functions in the SciLexer version of the edit control.
 **/
// Copyright 1998-2002 by Neil Hodgson <neilh@scintilla.org>
// The License.txt file describes the conditions under which this software may be distributed.

// Most of this file is automatically generated from the Scintilla.iface interface definition
// file which contains any comments about the definitions. HFacer.py does the generation.

#ifndef SCILEXER_H
#define SCILEXER_H

// SciLexer features - not in standard Scintilla

//++Autogenerated -- start of section automatically generated from Scintilla.iface
#define SCLEX_CONTAINER 0
#define SCLEX_RDO  1
#define SCLEX_FIND 2
#define SCLEX_BUILD 3
#define SCLEX_DEBUG 4
#define SCLEX_AUTOMATIC 1000
#define SCE_RDO_DEFAULT 0
#define SCE_RDO_IDENTIFIER 1
#define SCE_RDO_KEYWORD 2
#define SCE_RDO_FUNCTION 3
#define SCE_RDO_TRACE 4
#define SCE_RDO_COMMENT 5
#define SCE_RDO_NUMBER 6
#define SCE_RDO_STRING 7
#define SCE_RDO_OPERATOR 8
#define SCE_FIND_DEFAULT 0
#define SCE_FIND_IDENTIFIER 1
#define SCE_FIND_KEYWORD 2

//--Autogenerated -- end of section automatically generated from Scintilla.iface

#endif
